"""Planning-only composite-model lineage and portability evidence generator."""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PREFIX = "stage-10d-r14a-r1"
CONFIDENCE = {"PROVEN", "STRONGLY_SUPPORTED", "PARTIALLY_SUPPORTED", "UNRESOLVED", "CONTRADICTED"}
CLASSES = {"A_EXACT_RAW_REPRODUCIBLE", "B_EXACT_STATE_REPLAYABLE", "C_EXACT_HISTORICAL_OUTPUT_ONLY", "D_FORMULA_KNOWN_STATE_MISSING", "E_STATE_KNOWN_RAW_BUILDER_MISSING", "F_FEATURE_CONTRACT_KNOWN_PRODUCER_MISSING", "G_PARTIAL_RECOVERY_ONLY", "H_NOT_RECOVERABLE"}
ACTIONS = {"RECOVER_EXACT", "REIMPLEMENT_EXACT_FROM_SPEC", "REFIT_SAME_MODEL_FAMILY", "REBUILD_AS_NEW_VERSION", "DROP_FROM_PRODUCTION", "KEEP_HISTORICAL_ONLY"}


def git(*args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=ROOT, text=True).strip()


def write_json(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_csv(path: Path, fields: list[str], rows: list[dict]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader(); writer.writerows(rows)


def text(path: Path, value: str) -> None:
    path.write_text(value.strip() + "\n", encoding="utf-8")


def make_bundle(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=False)
    head, branch = git("rev-parse", "HEAD"), git("branch", "--show-current")
    dirty = [x for x in git("status", "--short").splitlines() if x]
    scope = {"stage": "Stage 10D-R14A-R1", "mode": "PLANNING_FORENSICS_ONLY", "active_codex_write_exception": "Stage 10D-R14A-R1", "production_changes": False, "generated_at_utc": datetime.now(timezone.utc).isoformat(), "repository_head": head}
    write_json(out / "task-scope.json", scope)
    write_json(out / f"{PREFIX}-preflight.json", {"branch": branch, "HEAD": head, "dirty_paths": dirty, "relevant_recent_commits": git("log", "--oneline", "--decorate", "-50").splitlines(), "available_branches": git("branch", "--all").splitlines(), "available_tags": git("tag", "--list").splitlines()})

    claims = [
        ("Historical winner was AC_FE_SYM_S30, a composite", "scripts/run_stage10d_r12g_r1.py:107 and evaluation/stage-10d-r6c-pre2026-fe-player-allocation-reassessment.json", "PROVEN"),
        ("Historical combination was additive S30 + delta_B + delta_O + delta_E", "scripts/run_stage10d_r12g_r1.py:107; historical model identity artifact", "PROVEN"),
        ("Exact AC_FE_SYM_S30 player-period predictions are absent", "scripts/run_stage10d_r12g.py:108-130 and R12G-R1 archive/git search", "PROVEN"),
        ("B2Z_V2 and OATS_V2 sealed state is present but their old raw-prelock producer is absent", "scripts/run_stage10d_r12c_r3.py:20; data/predictions/player_model_v2/model_state/*.json", "PROVEN"),
        ("Current frozen production player component is S30_V2 only", "scripts/run_stage10d_r12f_r3.py:100,181; current dashboard payload", "PROVEN"),
        ("S30_V2 is not identical to historical S30", "s30_v2 state target/features vs player_model_registry.py historical share correction", "PROVEN"),
        ("S30_V2 uses a repaired per-game target and is runnable", "scripts/run_stage10d_r12c_r2.py:35; model state", "PROVEN"),
        ("FE formula is known and raw builder exists, but historical parent/share parity is unavailable", "fantasy_prediction/fantasy_environment.py", "STRONGLY_SUPPORTED"),
    ]
    write_csv(out / f"{PREFIX}-claim-evidence-register.csv", ["claim", "evidence", "confidence"], [{"claim": a, "evidence": b, "confidence": c} for a,b,c in claims])

    identities = [
        {"identity":"S30","component_or_full_model":"component","first_seen":"Stage 9D-B","last_seen":"current registry","implementation_path":"fantasy_prediction/player_model_registry.py","fit_path":"historical share builder","state_path":"NOT_PERSISTED","prediction_path":"apply_s30_to_share_table","evaluation_artifact":"stage-9d-c-s30-end-to-end-fantasy-benchmark.json","formula_evidence":"T3 share correction λ=.30","training_cutoff_evidence":"historical only","status":"HISTORICAL_RESEARCH","notes":"Different model family from S30_V2"},
        {"identity":"AC_FE_SYM_S30","component_or_full_model":"full model","first_seen":"R6C","last_seen":"R12G-R1 forensic","implementation_path":"historical artifacts/scripts","fit_path":"NOT_PERSISTED","state_path":"NOT_PERSISTED","prediction_path":"NOT_PERSISTED","evaluation_artifact":"stage-10d-r6c-pre2026-fe-player-allocation-reassessment.json","formula_evidence":"S30_old + delta_B_old + delta_O_old + delta_E_old","training_cutoff_evidence":"pre-2026","status":"PROMOTED_HISTORICAL","notes":"No exact saved prediction table"},
        {"identity":"B2Z_V2_REPRODUCIBLE","component_or_full_model":"component","first_seen":"R12A","last_seen":"R12D","implementation_path":"fantasy_prediction/b2z_v2.py","fit_path":"historical sealed fit","state_path":"data/predictions/player_model_v2/model_state/b2z_v2_reproducible_2ee643edc5918ef0c52f3c7d4c4a3a8c8979971bbb9f789dc006fbafdd01bae4.json","prediction_path":"predict_delta","evaluation_artifact":"R12C-R3 validator","formula_evidence":"sealed ridge + non-support zero sum","training_cutoff_evidence":"2023-12-31","status":"REBUILD","notes":"Not prospective: producer missing"},
        {"identity":"OATS_V2_REPRODUCIBLE","component_or_full_model":"component","first_seen":"R12A","last_seen":"R12A","implementation_path":"fantasy_prediction/oats_v2.py","fit_path":"historical sealed fit","state_path":"data/predictions/player_model_v2/model_state/oats_v2_reproducible_6c0f41458ccba80694004806e237a4751db1770e285cd8f1a234e55d0c169587.json","prediction_path":"predict_delta","evaluation_artifact":"stage-10d-r5a-opponent-adjusted-team-strength-v2.json","formula_evidence":"sealed ridge on OATS state","training_cutoff_evidence":"2023-12-31","status":"REBUILD","notes":"Not wired to current production"},
        {"identity":"S30_V2_REPRODUCIBLE_R12C_R2_TARGET_GRAIN_REPAIR","component_or_full_model":"full model","first_seen":"R12C-R2","last_seen":"R12F-R3","implementation_path":"fantasy_prediction/s30_v2.py","fit_path":"scripts/fit_s30_v2.py","state_path":"data/predictions/player_model_v2/model_state/s30_v2_reproducible_7e12dfd6f0548ad11f44573f9e1a165c021f9910010d17e8906c0039935c62c5.json","prediction_path":"s30_v2.predict","evaluation_artifact":"stage-10d-r12c-s30-v2-evaluation.csv","formula_evidence":"sealed ridge","training_cutoff_evidence":"2023-12-31","status":"CURRENT_PRODUCTION","notes":"Per-game player-period target"},
    ]
    ident_fields = ["identity","component_or_full_model","first_seen","last_seen","implementation_path","fit_path","state_path","prediction_path","evaluation_artifact","formula_evidence","training_cutoff_evidence","status","notes"]
    write_csv(out / f"{PREFIX}-model-identity-inventory.csv", ident_fields, identities)
    write_csv(out / f"{PREFIX}-winning-model-evidence.csv", ["stage","candidate_id","formula","evaluation_period","player_MAE","team_MAE","ranking_metric","fantasy_lineup_score","promotion_decision","artifact_path","confidence"], [{"stage":"R6C","candidate_id":"AC_FE_SYM_S30","formula":"S30 + delta_B + delta_O + delta_E","evaluation_period":"pre-2026 pooled","player_MAE":"5.0079194214 (S30 reference; component table governs selection)","team_MAE":"21.76525893297 (symmetric FE reference)","ranking_metric":"player MAE with protected team-MAE evidence","fantasy_lineup_score":"NOT_COMPARABLE","promotion_decision":"historical operational baseline pending unseen holdout","artifact_path":"data/predictions/player_model_v2/evaluation/stage-10d-r6c-pre2026-fe-player-allocation-reassessment.json","confidence":"STRONGLY_SUPPORTED"}])

    graph = """# Winning historical composite graph

`AC_FE_SYM_S30` is the strongest evidenced historical research/operational baseline. Its formula is additive, but its inputs are not interchangeable.

Raw Oracle/player history -> historical S30 share correction -> S30
\nStage 3E player rating + Stage 4C context + Stage 8 team/core/matchup state -> B2Z ridge -> support-protected team-zero-sum delta_B
\nOATS sequential ratings + team-period calibration frame -> OATS ridge -> delta_O
\ncompleted team combat history -> FE1 centered (window 5) -> alpha_E * FE1 * S30_share -> delta_E
\nS30 + delta_B + delta_O + delta_E -> AC_FE_SYM_S30 player-period prediction.

The historical B2Z/OATS state-to-feature edges have no checked-in arbitrary raw/pre-lock producer; therefore this graph is historical, not prospective."""
    text(out / f"{PREFIX}-winning-model-graph.md", graph)
    text(out / f"{PREFIX}-winning-model-graph.mmd", "graph TD\nRAW[Immutable pre-lock raw]-->S30[S30 historical share]\nRAW-->STATE[Stage 3E/4C/8 context]\nSTATE-->B2Z[B2Z delta_B]\nRAW-->OATSSTATE[OATS rating/context]\nOATSSTATE-->OATS[OATS delta_O]\nRAW-->FE[FE1 centered * S30 share]\nS30-->FINAL[AC_FE_SYM_S30]\nB2Z-->FINAL\nOATS-->FINAL\nFE-->FINAL")
    nodes = [
        ("raw_oracle","RAW_SOURCE","game/player/team","normalized raw","Oracle schema","canonical rows","data/raw/oracles_elixir","none","none","strictly pre-lock","yes","yes"),
        ("historical_s30","PREDICTION","player-period","player score/share","share table","S30","player_model_registry.py","historical T3/share state","historical rows","historical cutoff","yes","no"),
        ("stage3e_4c_8_context","FEATURE_BUILDER","player-period","15 B2Z fields","NOT_PERSISTED","serialized feature frame","stage4c context builder","Stage 3E/4C/8","unknown","pre-lock claimed","unknown","no"),
        ("b2z","PREDICTION","player-period/team","delta_B","15 fields","delta","b2z_v2.py","sealed B2Z state","2023 cutoff","explicit","yes","no"),
        ("oats","PREDICTION","team-period","delta_O","5 fields","delta","oats_v2.py","sealed OATS state","2023 cutoff","explicit","yes","no"),
        ("fe","TRANSFORM","team-period -> player","delta_E","FE1,S30 share","delta","fantasy_environment.py","alpha_E=1.690769","pre-2026","strictly pre-lock","yes","partial"),
        ("final","AGGREGATOR","player-period","prediction","component deltas","AC_FE_SYM_S30","historical lineage artifact","all component states","historical","same period","yes","no"),
    ]
    write_csv(out / f"{PREFIX}-node-audit.csv", ["node_id","node_type","input_grain","output_grain","input_schema","output_schema","implementation_file/function","state_dependency","training_dependency","cutoff_semantics","deterministic","future-runnable","evidence"], [{"node_id":a,"node_type":b,"input_grain":c,"output_grain":d,"input_schema":e,"output_schema":f,"implementation_file/function":g,"state_dependency":h,"training_dependency":i,"cutoff_semantics":j,"deterministic":k,"future-runnable":l,"evidence":"repository source and R12C/R12G evidence"} for a,b,c,d,e,f,g,h,i,j,k,l in nodes])
    edges = [("raw_oracle","historical_s30","canonical share columns","player-period","player_id,period","chronological","T3/share","cutoff","player_model_registry.py","false","false","historical S30 state missing"),("stage3e_4c_8_context","b2z","15 B2Z fields","player-period","player_id,team_id,period","pre-lock","B2Z state","cutoff","b2z_v2.py","false","false","missing raw producer"),("raw_oracle","oats","rating/calibration fields","team-period","team_id,period","sequential","OATS state","cutoff","oats_v2.py","false","false","missing calibration materializer"),("raw_oracle","fe","team combat history","team-period","team_id,series","chronological","alpha_E","cutoff","fantasy_environment.py","true","true","historical parent share differs"),("historical_s30","final","S30","player-period","player_id,period","same period","none","same cutoff","historical formula","false","false","S30 historical state absent"),("b2z","final","delta_B","player-period","player_id,period","same period","none","same cutoff","historical formula","false","false","upstream unavailable"),("oats","final","delta_O","team-period","team_id,period","same period","none","same cutoff","historical formula","false","false","upstream unavailable"),("fe","final","delta_E","player-period","player_id,period","same period","S30_share","same cutoff","fantasy_environment.py","partial","partial","requires equivalent S30 share")]
    write_csv(out / f"{PREFIX}-edge-audit.csv", ["from_node","to_node","required_columns","key_grain","join_keys","ordering_requirement","state_dependency","cutoff_dependency","implementation_path","exactly_reproducible","future_reproducible","blocker","evidence"], [{"from_node":a,"to_node":b,"required_columns":c,"key_grain":d,"join_keys":e,"ordering_requirement":f,"state_dependency":g,"cutoff_dependency":h,"implementation_path":i,"exactly_reproducible":j,"future_reproducible":k,"blocker":l,"evidence":"R12C-R3 / source"} for a,b,c,d,e,f,g,h,i,j,k,l in edges])

    contracts = [("S30","share reallocation","T3 + share correction","player score","historical share columns","historical canonical","player-period","unknown","NOT_PERSISTED","NOT_PERSISTED","NOT_PERSISTED","historical rows","historical","NOT_APPLICABLE","NOT_PERSISTED","player-period","team-total-preserving","S30","final"),("B2Z","within-team residual allocation","ridge residual then zero sum","residual","15 sealed fields","state feature_order","player-period","median/standardize/role dummies","sealed","sealed","alpha=10","through 2023","2023-12-31","NOT_APPLICABLE","sealed JSON","player-period","SUP 0; non-SUP zero sum","delta_B","final"),("OATS","team residual calibration","ridge team residual","team residual","5 sealed fields","state feature_order","team-period","median/standardize","sealed","sealed","alpha=1","through 2023","2023-12-31","NOT_APPLICABLE","sealed JSON","team-period","NOT_APPLICABLE","delta_O","final"),("FE","fantasy environment","alpha_E*FE1_centered*S30_share","team combat opportunity","team kills/opponent deaths/share","NOT_APPLICABLE","team->player","centering","NOT_APPLICABLE","alpha_E=1.690769","NOT_APPLICABLE","pre-2026 selection","window 5","5 games","formula code","player-period","S30 share allocation","delta_E","final")]
    cfields=["component","purpose","formula","target","features","feature_order","feature_grain","target_grain","preprocessing","scaler","intercept","coefficients","regularization","training_data","training_cutoff","lookback","state_path","prediction_unit","allocation_logic","output_name","downstream_consumer"]
    write_csv(out / f"{PREFIX}-component-contracts.csv", cfields, [dict(zip(cfields, r)) for r in contracts])
    text(out / f"{PREFIX}-s30-lineage.md", "# S30 lineage\n\nHistorical S30 is a T3 historical-share correction (`lambda=.30`) that preserves team totals. S30_V2 is a new ridge family: six five-game raw form features, median imputation, standardization, role dummies, alpha=.1, intercept=13.8031058751, trained through 2023-12-31 for a player × local-period game-average target. Relationship: `NEW_MODEL`, not identical nor a refit of historical S30. Current production uses S30_V2.")
    text(out / f"{PREFIX}-b2z-lineage.md", "# B2Z lineage\n\nB2Z_V2 state preserves alpha=10, the 15-field order, role coupling, support protection, and centered within-team residual target. It depends on `prior_player_rating`, `prior_role_relative_rating`, `prior_role_adjusted_kp`, `prior_starter_reliability`, `prior_effective_evidence`, `prior_residual_uncertainty`, `prior_core_state`, `prior_team_state`, `prior_team_strength`, `team_continuity`, `predicted_team_win_probability`, and `matchup_strength_diff` from Stage 3E/4C/8 lineage. No checked-in arbitrary raw/pre-lock producer materializes these; B2Z_V2 is state-replayable only when an already equivalent frame exists and is not future-runnable.")
    text(out / f"{PREFIX}-oats-lineage.md", "# OATS lineage\n\nOATS sequential rating equation is `R_post=R_pre+K*(result-p_pre)`, selected K=48/carryover=.75. OATS_V2 uses five calibrated team residual features and sealed alpha=1 state. It is a reproducible successor state, not proof of historical equivalence: the historical calibration/input frame is unavailable as a raw future builder. Any refit is a new version/model ID.")
    text(out / f"{PREFIX}-fe-lineage.md", "# FE lineage\n\nFE1 = .5*(team five-game kills + opponent five-game deaths), centered on pre-lock league mean. Historical symmetric allocation is `delta_E = 1.690769 * FE1_centered * S30_share`; history window=5, split reset enabled. FE raw builder is present. Historical FE is only exact when historical S30 share is available; substituting S30_V2 requires `PROSPECTIVE_FE_WITH_NEW_BASE`, a new model identity.")
    text(out / f"{PREFIX}-final-combination-contract.md", "# Final combination contract\n\nRepository evidence proves the historical formula: `AC_FE_SYM_S30 = S30_old + delta_B_old + delta_O_old + delta_E_old`. B2Z applies support protection and a non-support team-zero-sum projection before addition. FE is centered and allocated via historical S30 share before addition. No evidence supports post-addition multiplicative scaling, clipping, or refitting. The historical formula cannot be prospectively re-created because component-input edges, not merely states, are missing.")

    matrix=[("historical S30","D_FORMULA_KNOWN_STATE_MISSING","yes","no","partial","no","no","no","no","no","share/T3 historical state"),("B2Z_V2","E_STATE_KNOWN_RAW_BUILDER_MISSING","yes","yes","no","no","partial","no","conditional","no","Stage 3E/4C/8 producer"),("OATS_V2","E_STATE_KNOWN_RAW_BUILDER_MISSING","yes","yes","partial","no","partial","no","conditional","no","calibration context producer"),("FE historical","G_PARTIAL_RECOVERY_ONLY","yes","partial","yes","yes","partial","no","no","conditional","historical S30 share"),("AC_FE_SYM_S30","H_NOT_RECOVERABLE","yes","no","no","no","no","no","no","no","all historical transitions/predictions absent"),("S30_V2","A_EXACT_RAW_REPRODUCIBLE","yes","yes","yes","yes","yes","yes","yes","yes","none")]
    mf=["component_or_node","classification","formula_available","state_available","raw_builder_available","future_builder_available","historical_output_available","historical_predictions_available","exact_replay_possible","future_prediction_possible","blocker","evidence"]
    write_csv(out / f"{PREFIX}-reproducibility-matrix.csv", mf, [dict(zip(mf, list(x)+["source + R12 evidence"])) for x in matrix])
    text(out / f"{PREFIX}-irreplicable-calculations.md", "# Precise irreproducible calculations\n\n- Historical S30: missing historical T3 prediction/share inputs and its fitted/share state; consumed by every final component and FE allocation. Git/history exposes the consumer but no complete state/table. Rebuilding makes a new model.\n- B2Z transition: no raw producer for the 12 named Stage 3E/4C/8 player/core/team/matchup fields. Sealed coefficients exist, but cannot produce a future input frame.\n- OATS calibration transition: rating context and calibration table needed by sealed five-field model are not preserved as an arbitrary pre-lock materializer.\n- Final historical output: no exact `AC_FE_SYM_S30` player-period prediction table found in current tree, all refs, archives, or prior R12G forensic inventory.\n\nThese are formula/edge/state losses, not merely an unavailable file path.")
    write_csv(out / f"{PREFIX}-git-forensics.csv", ["commit","date","path","artifact_type","component","relevance","recoverable","exact_or_partial","notes"], [{"commit":"f1d684a","date":"history","path":"historical player-model scripts","artifact_type":"source","component":"AC/OATS","relevance":"lineage lead","recoverable":"yes","exact_or_partial":"partial","notes":"consumer/formula evidence, not complete state"},{"commit":"818bdb5","date":"current","path":"scripts/run_stage10d_r12g_r1.py","artifact_type":"forensic script","component":"AC_FE_SYM_S30","relevance":"searched all refs/archives","recoverable":"no","exact_or_partial":"exact finding","notes":"no exact old table"}])
    write_csv(out / f"{PREFIX}-evidence-forensics.csv", ["path","artifact_type","component","finding","usable_for_exact_replay"], [{"path":".agent-runs/player-model-v2-stage-10d-r12g-r1-old-artifact-forensics-20260821T201000Z","artifact_type":"forensic packet","component":"AC_FE_SYM_S30","finding":"no exact player-period table","usable_for_exact_replay":"no"},{"path":"data/predictions/player_model_v2/model_state/*.json","artifact_type":"sealed state","component":"S30_V2/B2Z_V2/OATS_V2","finding":"states survive","usable_for_exact_replay":"conditional"}])
    write_csv(out / f"{PREFIX}-historical-prediction-inventory.csv", ["model_id","artifact_path","years","periods","row_count","prediction_grain","prediction_unit","target_column","model_identity_proven","usable_for_head_to_head"], [{"model_id":"AC_FE_SYM_S30","artifact_path":"NOT_FOUND","years":"UNKNOWN","periods":"UNKNOWN","row_count":"0","prediction_grain":"UNKNOWN","prediction_unit":"UNKNOWN","target_column":"UNKNOWN","model_identity_proven":"yes (lineage only)","usable_for_head_to_head":"no"},{"model_id":"S30_V2_REPRODUCIBLE_R12C_R2_TARGET_GRAIN_REPAIR","artifact_path":"data/predictions/player_model_v2/evaluation/stage-10d-r12c-s30-v2-evaluation.csv","years":"2024-2025","periods":"evaluation rows","row_count":"see source","prediction_grain":"player local period","prediction_unit":"game average","target_column":"realized_fantasy_target","model_identity_proven":"yes","usable_for_head_to_head":"no (old rows absent)"}])

    text(out / f"{PREFIX}-current-production-call-path.md", "# Current production call path\n\nImmutable Oracle history -> `scripts/build_s30_v2_raw_modeling_table.py`/stored raw table -> `fantasy_prediction.s30_v2.predict` using frozen R12C-R2 state -> player weekend score interpreted as game-average -> frozen coach producer -> champion portfolio + official market + schedule/conflict graph -> `fantasy_prediction.lineup_optimizer` -> dashboard lineup payload. B2Z, OATS, and FE are explicitly absent from frozen R12F-R3 player formula.")
    write_json(out / f"{PREFIX}-current-production-model.json", {"model_id":"S30_V2_REPRODUCIBLE_R12C_R2_TARGET_GRAIN_REPAIR","formula":"S30_V2 sealed ridge only","active_components":["S30_V2"],"state_paths":["data/predictions/player_model_v2/model_state/s30_v2_reproducible_7e12dfd6f0548ad11f44573f9e1a165c021f9910010d17e8906c0039935c62c5.json"],"feature_builders":["scripts/build_s30_v2_raw_modeling_table.py"],"training_cutoffs":"2023-12-31T23:59:59Z","data_window":"five completed games","unit":"player-period game average / weekend average","team_matchup_usage":False,"carry_usage":False,"FE_usage":False,"B2Z_usage":False,"OATS_usage":False,"prospective_runnable":True})
    gap_rows=[("baseline player form","historical S30 share correction","S30_V2 ridge","different","new target/features","retain separately"),("within-team allocation","B2Z delta_B","absent","different","missing producer","rebuild new version"),("team/opponent strength","OATS delta_O","absent","different","missing producer","rebuild new version"),("fantasy environment","FE delta_E","absent","different","historical share unavailable","new-base candidate"),("state persistence","incomplete historic","S30_V2 sealed","different","historic portability failure","promotion contract"),("historical prediction persistence","absent old table","some new evaluation","different","cannot compare","persist every run")]
    write_csv(out / f"{PREFIX}-research-vs-production-gap.csv", ["historical_winning_behavior","current_production_behavior","same_or_different","expected_quality_impact","portability_reason","recommended_action"], [dict(zip(["historical_winning_behavior","current_production_behavior","same_or_different","expected_quality_impact","portability_reason","recommended_action"], x)) for x in gap_rows])

    data_rows=[("data/raw/oracles_elixir","Oracle's Elixir","game/player/team","2014","2026","multiple","normalized by pipeline","multi-split","yes","source-dependent","league naming gaps"),("data/raw/official_market_snapshots","official market","player-round","2026","2026","LCS/LTA","market labels","2026 rounds","yes","yes when captured","no official archive"),("data/raw/fantasy_actuals","official observations","roster/game","2026","2026","LTA","project labels","limited","yes","post-result only","incomplete historical coverage"),("data/processed/player_model_v2","processed modeling tables","player-period","2020","2025/2026","normalized","normalized","selected tables","rebuildable","depends on builder","staleness/target-grain history"),("data/predictions/player_model_v2/model_state","sealed fitted state","model","2023","2023","N/A","N/A","N/A","yes","yes","B2Z/OATS inputs absent")]
    write_csv(out / f"{PREFIX}-data-inventory.csv", ["path","source","grain","earliest_date","latest_date","league_raw","league_normalized","split_coverage","immutable","cutoff_safe","known_gaps"], [dict(zip(["path","source","grain","earliest_date","latest_date","league_raw","league_normalized","split_coverage","immutable","cutoff_safe","known_gaps"],x)) for x in data_rows])
    write_csv(out / f"{PREFIX}-data-staleness-audit.csv", ["component","raw_latest_date_available","processed_latest_date_used","training_latest_date","reason_for_gap","intentional_or_bug"], [{"component":"S30_V2 pre-R12C","raw_latest_date_available":"newer raw existed","processed_latest_date_used":"calendar-week-sum table","training_latest_date":"2023","reason_for_gap":"target grain / stale processed contract","intentional_or_bug":"BUG"},{"component":"S30_V2 repaired","raw_latest_date_available":"2026 raw exists","processed_latest_date_used":"R12C corrected table","training_latest_date":"2023-12-31","reason_for_gap":"frozen architecture/training cutoff","intentional_or_bug":"intentional"},{"component":"B2Z/OATS","raw_latest_date_available":"2026 raw exists","processed_latest_date_used":"serialized historic context","training_latest_date":"2023-12-31","reason_for_gap":"missing materializer","intentional_or_bug":"portability gap"}])
    text(out / f"{PREFIX}-canonical-point-in-time-architecture.md", "# Canonical architecture proposal\n\nImmutable raw Oracle, schedule, and market snapshots -> versioned identity/schedule/market normalization -> rebuildable point-in-time player, team, opponent, and FE tables keyed by `(prediction_period_id, team_id, player_id, lock_timestamp)` -> versioned component feature builders -> immutable fitted-state bundle with schema/hash -> arbitrary unlabeled future frame -> game-average/weekend-average prediction export. Proposed modules: `fantasy_prediction/pit_frames.py`, `player_context_features.py`, `team_context_features.py`, `component_runtime.py`, `model_bundle.py`; this is a proposal only.")
    plans=[("historical S30","KEEP_HISTORICAL_ONLY","state/share inputs missing","historical prediction/share table","formula evidence","none","yes","no"),("S30_V2","RECOVER_EXACT","state+builder survive","raw history, frozen state","state/schema/hash","nothing","yes","yes"),("B2Z","REBUILD_AS_NEW_VERSION","producer cannot be recovered exactly","canonical raw PIT context","new raw builder/state","historical model ID","yes","yes"),("OATS","REBUILD_AS_NEW_VERSION","calibration transition unavailable","canonical team PIT context","new state/schema","historical model ID","yes","yes"),("FE","REIMPLEMENT_EXACT_FROM_SPEC","formula/raw builder survive","team history + new base share","FE formula/alpha provenance","parent identity","yes","yes"),("AC_FE_SYM_S30","KEEP_HISTORICAL_ONLY","no exact replay/predictions","all historical components","historical evidence","nothing","yes","no")]
    write_csv(out / f"{PREFIX}-component-recovery-plan.csv", ["component","action","reason","required_inputs","what_must_be_preserved","what_may_change","historical_validation_required","future_smoke_test_required"], [dict(zip(["component","action","reason","required_inputs","what_must_be_preserved","what_may_change","historical_validation_required","future_smoke_test_required"],x)) for x in plans])
    value_fields = ["component", "historical evidence", "later reproducible evidence", "conflict", "recommended interpretation"]
    value_rows = [
        ("B2Z", "historical member", "R12D prospective retirement due to missing producer", "none: portability not quality", "do not restore as historical ID"),
        ("OATS", "historical member", "later OATS qualified/research but no equivalent frame", "quality incomparable", "new candidate only"),
        ("FE", "historical member/best symmetric evidence", "later symmetric FE best but dependent on base", "base changed", "revalidate after base frozen"),
    ]
    write_csv(out / f"{PREFIX}-component-value-evidence.csv", value_fields, [dict(zip(value_fields, row)) for row in value_rows])
    text(out / f"{PREFIX}-historical-parity-plan.md", "# Historical parity plan\n\n1. Data parity: hashes, identities, target, and cutoff. 2. Feature parity: retained historical rows only. 3. Component parity: compare S30/delta_B/delta_O/delta_E wherever exact outputs survive. 4. Final parity: only if exact old final predictions are recovered. 5. Performance parity: same rows/unit, player/team MAE, bias, Pearson, Spearman, roles. If state/edge is absent label `PARITY_PARTIAL` or `NEW_VERSION_REQUIRED`; never call a refit historical parity.")
    text(out / f"{PREFIX}-production-refresh-plan.md", "# Production refresh plan\n\nChoose architecture/hyperparameters on fixed historical development/confirmation periods; freeze formula/schema; then batch-refit final production state on all completed legal pre-lock data; seal hashes; run target-free future smoke test; publish. S30_V2: `REFIT_BATCH`; new B2Z/OATS: `REFIT_BATCH` (or explicitly documented sequential ratings followed by batch calibration); FE: `LOAD_FIXED_STATE` alpha after selection. No fitting at prediction time.")
    text(out / f"{PREFIX}-new-data-integration-contract.md", "# New-data integration contract\n\nRaw files are immutable; normalization/versioned PIT tables rebuild from raw; no manual append to frozen tables. Every refresh records `RAW_LATEST_DATE`, `PROCESSED_LATEST_DATE`, and `TRAINING_LATEST_DATE`; an unexplained gap fails refresh. Cutoffs/manifests/hashes are explicit.")
    text(out / f"{PREFIX}-future-period-smoke-test-contract.md", "# Target-free future-period smoke test\n\nGiven only raw history, official schedule, market snapshot, and lock timestamp, produce 100% eligible-player coverage with no target column, no post-lock records, no prediction-time fitting, exact training schema, and deterministic replay. Failure verdict: `NOT_PRODUCTION_READY`.")
    text(out / f"{PREFIX}-proposed-model-promotion-contract.md", "# Proposed promotion contract\n\nA promoted model must have immutable ID; serialized state; feature order/schema; preprocessing; raw pre-lock materializer; arbitrary-future API; target/unit; cutoff/manifest; no prediction-time fit; deterministic replay; target-free smoke pass; persisted historical predictions; hashes; export parity; rollback lineage. Hard rule: `HISTORICAL_EVALUATION_PASS != PRODUCTION_READY`. Proposed future homes: AGENTS.md, docs/agent/model-promotion-contract.md, tests/test_model_promotion_contract.py (not edited here).")
    vet=[("raw data","raw manifest","hash/date inventory","exact","fail refresh","yes"),("feature builder","unlabeled future frame","schema parity","exact","NOT_PRODUCTION_READY","yes"),("component state","sealed JSON","hash + no fit","exact","reject promotion","yes"),("full model","historical rows","MAE/bias/rank","declared","PARITY_PARTIAL","yes"),("historical prediction persistence","prediction table","rows/id/unit","exact","reject promotion","yes")]
    write_csv(out / f"{PREFIX}-vetting-matrix.csv", ["test_name","input","expected_output","tolerance","failure_verdict","required_before_promotion"], [dict(zip(["test_name","input","expected_output","tolerance","failure_verdict","required_before_promotion"],x)) for x in vet])
    text(out / f"{PREFIX}-proposed-production-architecture.md", "# Proposed production architecture\n\nResearch: historical raw -> PIT contexts -> candidate architecture -> fixed confirmation -> decision.\n\nProduction refit: frozen architecture -> all legal completed pre-lock data -> sealed state.\n\nInference: sealed state + raw history + schedule + market + lock -> unlabeled feature frame -> player predictions.\n\nThe same materializers serve research and future inference; this removes the historical fork that caused portability loss.")
    text(out / f"{PREFIX}-roadmap.md", "# Exact roadmap\n\n1. **R14B — Canonical raw/PIT data layer.** Inputs raw/schedule/market; writes only new PIT modules/tests; gate: arbitrary unlabeled frame with date parity; stop on missing identity/schedule contract; next R14C.\n2. **R14C — Rebuild components as new versions.** Inputs frozen PIT frames; writes candidate modules/state/tests; gate: component historical/no-component comparisons; stop on leakage/schema failure; next R14D.\n3. **R14D — parity and selection gate.** Gate: declared parity classification and frozen architecture; stop if no common rows.\n4. **R14E/F — seal/refit production state.** Batch refit after architecture freeze; gate hashes/manifests.\n5. **R14G — target-free smoke test.** Gate 100% coverage/deterministic replay; failure not production ready.\n6. **R14H — retrospective counterfactual.** Only after parity/production gates.\n7. **R15 — new improvements.**\n\nImmediate next node: **R14B**.")
    completion = """# STAGE_10D_R14A_R1_COMPOSITE_MODEL_GROUND_TRUTH_AND_PORTABILITY_PLAN_COMPLETE

## Executive ground truth

The strongest evidenced historical configuration was composite `AC_FE_SYM_S30`: historical S30 plus B2Z, OATS, and symmetric FE deltas. Current frozen production is the repaired, runnable `S30_V2` ridge alone. They diverged because the historical graph preserved formulas and some states but not the raw-to-context producers or final prediction tables.

## Graph and contracts

The winning formula is additive: `S30_old + delta_B_old + delta_O_old + delta_E_old`. B2Z applies support protection/zero-sum allocation before combination; FE is centered and allocated through historical S30 share. The graph, contracts, nodes, and edges are separately recorded in this packet.

## Reproducibility

S30_V2 is exact/raw reproducible. B2Z_V2/OATS_V2 sealed states are not future runnable because Stage 3E/4C/8 player/core/team/matchup and calibration materializers are absent. Historical S30 and AC_FE_SYM_S30 lack required state/output persistence. No exact AC_FE_SYM_S30 player-period prediction table survives, so strict old-vs-new comparison is permanently unavailable unless a new archive source emerges.

## Data and recovery

Usable raw Oracle coverage reaches 2026, market/actual captures are 2026-limited, and older processed tables had a proven target-grain/staleness defect. Do not resurrect B2Z/OATS under historic names: rebuild them as versioned new models on a canonical point-in-time frame. FE can be reimplemented from its known specification only as a new-base candidate.

## Portability gate and roadmap

Future promotion requires state, schema, raw materializer, persisted predictions, deterministic replay, and a completely target-free future-period smoke test. Historical evaluation alone is never production readiness. The one recommended immediate next node is **R14B — canonical raw / point-in-time data layer**. No model rebuild, refit, or production behavior change was performed.
"""
    text(out / f"{PREFIX}-completion-report.md", completion)
    text(out / "self-review.md", "# Self-review\n\n- Planning/evidence files only; no production code changed.\n- Historic and current model identities kept distinct.\n- No unsupported parity or quality claim made.\n- Required missing producers named explicitly.\n- Immediate next node is exactly R14B.")
    write_json(out / f"{PREFIX}-test-summary.json", {"script":"scripts/audit_stage10d_r14a_r1.py","focused_test":"tests/test_stage10d_r14a_r1_audit.py","checks":["enum validity","required artifact names","nonblank critical contract fields","unique graph nodes","edge endpoint coverage"],"passed":"pending invocation"})
    manifest={p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in out.iterdir() if p.is_file() and p.name != "manifest-sha256.json"}
    write_json(out / "manifest-sha256.json", manifest)


def validate_bundle(out: Path) -> list[str]:
    required=[f"{PREFIX}-completion-report.md",f"{PREFIX}-model-identity-inventory.csv",f"{PREFIX}-node-audit.csv",f"{PREFIX}-edge-audit.csv",f"{PREFIX}-component-contracts.csv",f"{PREFIX}-reproducibility-matrix.csv",f"{PREFIX}-roadmap.md"]
    errors=[f"missing {x}" for x in required if not (out/x).exists()]
    if errors:
        return errors
    with (out/f"{PREFIX}-reproducibility-matrix.csv").open(encoding="utf-8") as h:
        errors += ["invalid reproducibility class"] if any(r["classification"] not in CLASSES for r in csv.DictReader(h)) else []
    with (out/f"{PREFIX}-component-recovery-plan.csv").open(encoding="utf-8") as h:
        errors += ["invalid recovery action"] if any(r["action"] not in ACTIONS for r in csv.DictReader(h)) else []
    return errors


if __name__ == "__main__":
    parser=argparse.ArgumentParser(); parser.add_argument("--out", type=Path, required=True); args=parser.parse_args(); make_bundle(args.out)
    failures=validate_bundle(args.out)
    if failures: raise SystemExit("; ".join(failures))
