#!/usr/bin/env python3
"""R5D-R1 common-universe authority remediation; frozen candidates only."""
from __future__ import annotations
import argparse, hashlib, json, subprocess, sys, tomllib
from pathlib import Path
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from evaluate_stage10d_r3c2 import calibration,rank,shares
from evaluate_stage10d_r4a import thresholds
from fantasy_prediction.s30_oats import fit_predict
E=ROOT/'data/predictions/player_model_v2/evaluation';P='stage-10d-r5d-r1';K=['prediction_period_id','target_cutoff','player_id','team','role'];R5A=ROOT/'.agent-runs/player-model-v2-stage-10d-r5a-opponent-adjusted-team-strength-20260814T160638Z'
def d(o):
 if isinstance(o,np.integer):return int(o)
 if isinstance(o,np.floating):return float(o)
 if isinstance(o,np.bool_):return bool(o)
 raise TypeError(type(o).__name__)
def dump(p,x):p.write_text(json.dumps(x,indent=2,sort_keys=True,default=d)+'\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def active():
 c=tomllib.loads((ROOT/'.codex/config.toml').read_text());e=tomllib.loads((ROOT/'.codex/policy-exceptions/stage-10d-r5d.toml').read_text());return c['model']=='gpt-5.6-terra' and c['model_reasoning_effort']=='medium' and c['agents'].get('policy_exception')=='.codex/policy-exceptions/stage-10d-r5d.toml' and e['active'] and e['write_capable_agents']==['r5d_r1_direct_codex'] and not e['recursive_delegation_allowed']
def met(x,c):
 x=x.copy();x['team_id']=x.team;q={**calibration(x,c),**rank(x,c,thresholds(x)),**shares(x,c)};er=(x[c]-x.actual).abs();t=x.groupby(['prediction_period_id','team'])[[c,'actual']].sum();te=t[c]-t.actual
 q.update(tail10=float((er>=10).mean()),tail15=float((er>=15).mean()),prediction_SD=float(x[c].std(ddof=0)),actual_SD=float(x.actual.std(ddof=0)),prediction_actual_SD_ratio=float(x[c].std(ddof=0)/x.actual.std(ddof=0)),team_total_MAE=float(te.abs().mean()),team_total_RMSE=float(np.sqrt(np.mean(te**2))),team_total_bias=float(te.mean()),team_total_Spearman=float(t[c].rank().corr(t.actual.rank())))
 for r,g in x.groupby('role'):q[f'{r}_MAE']=float((g[c]-g.actual).abs().mean())
 return q
def stats(x):return {'rows':len(x),'period_count':int(x.prediction_period_id.nunique()),'team_period_count':int(x.drop_duplicates(['prediction_period_id','team']).shape[0]),'role_counts':x.role.value_counts().sort_index().to_dict(),'year_counts':x.year_authority.value_counts().sort_index().to_dict(),'duplicate_keys':int(x.duplicated(K).sum())}
def score(x,cols,u):
 return pd.DataFrame([{'universe_id':u,'candidate':n,'authority_period':z,**met(x[m],c)} for z,m in [('2022_2023',x.year_authority.isin([2022,2023])),('2024',x.year_authority.eq(2024)),('2025',x.year_authority.eq(2025))] for n,c in cols.items()])
def replay(full):
 st=pd.read_csv(E/'stage-10d-r5a-oats-prelock-team-state.csv');g=pd.read_csv(ROOT/'data/processed/player_model_v2/stage_3e_03/postperiod_player_game_results.csv',usecols=['series_id','prediction_period_id','team_id']).drop_duplicates();mp=st[['series_id','team_id']].drop_duplicates().merge(g,on=['series_id','team_id'],how='left').dropna().drop_duplicates(['prediction_period_id','team_id']);st=st.drop(columns='prediction_period_id').merge(mp,on=['series_id','team_id'],how='inner')
 x=full.rename(columns={'team':'team_id'}).merge(st,on=['prediction_period_id','team_id'],how='inner',validate='many_to_one');x['S30_team_total']=x.groupby(['prediction_period_id','team_id']).S30_prediction.transform('sum');t=x.groupby(['prediction_period_id','team_id'],as_index=False).agg(actual_team_total=('actual','sum'),S30_team_total=('S30_team_total','first'),year=('year_authority','first'),rating_delta=('rating_delta','first'),oats_win_probability=('oats_win_probability','first'),season_actual_minus_expected_wins=('season_actual_minus_expected_wins','first'),recent_schedule_strength_percentile=('recent_schedule_strength_percentile','first'));t['team_residual']=t.actual_team_total-t.S30_team_total;t['S30_OATS_team_total']=t.S30_team_total
 for y in (2022,2023,2024,2025):
  tr=t[t.year.lt(y)];sc=t[t.year.eq(y)]
  if len(tr)>=5:t.loc[sc.index,'S30_OATS_team_total']=sc.S30_team_total+fit_predict(tr,sc,1)
 x=x.merge(t[['prediction_period_id','team_id','S30_OATS_team_total']],on=['prediction_period_id','team_id']);x['reconstructed_prediction']=x.S30_OATS_team_total*x.S30_prediction/x.S30_team_total;return x.rename(columns={'team_id':'team'}),mp
def run(out,tracked):
 if not active():raise SystemExit('BLOCKED_BY_DIRECT_CODEX_POLICY')
 out.mkdir(parents=True,exist_ok=False);subprocess.run([str(ROOT/'.venv/bin/python'),'scripts/validate_agent_harness.py'],cwd=ROOT,check=True)
 files={'B2Z_NS':E/'stage-10d-r5b-r2-final-b2z-ns-predictions.csv','P1':E/'stage-10d-r5c-r1-final-p1-adjustments.csv','S30_OATS':E/'stage-10d-r5a-s30-oats-predictions.csv'};b,p,o=(pd.read_csv(files[z]) for z in files)
 for x in (b,p,o):x.target_cutoff=pd.to_datetime(x.target_cutoff,utc=True)
 lab=pd.read_csv(ROOT/'data/processed/player_model_v2/stage_3e_03/modeling_table.csv',usecols=['player_id','team_id','role','prediction_period_id','participated','realized_fantasy_points']);lab=lab[lab.participated.astype(str).str.lower().eq('true')].rename(columns={'team_id':'team','realized_fantasy_points':'actual'});lab.role=lab.role.str.upper();s=b.merge(lab,on=['player_id','team','role','prediction_period_id'],how='left',validate='one_to_one');s['derived_year']=s.target_cutoff.dt.year
 if s.actual.isna().any() or not s.derived_year.eq(s.year_authority).all():raise SystemExit('BLOCKED_BY_AUTHORITATIVE_YEAR_PARTITION')
 part=s.groupby('derived_year').size().rename('row_count').reset_index().rename(columns={'derived_year':'year_authority'});part.to_csv(out/f'{P}-authoritative-year-partition.csv',index=False);partj={'year_counts':{str(int(r.year_authority)):int(r.row_count) for r in part.itertuples(False)},'2022_2025_total':int(s.derived_year.between(2022,2025).sum()),'2022_2026_total':int(s.derived_year.between(2022,2026).sum()),'authority_fields':['target_cutoff','prediction_period_id','year_authority']};dump(out/f'{P}-authoritative-year-partition.json',partj)
 full=s[s.derived_year.between(2022,2025)].copy();full['year_authority']=full.derived_year;full[K+['year_authority']].to_csv(out/f'{P}-full-pre2026-universe.csv',index=False);fj=stats(full);fj.update({'universe_id':'FULL_PRE2026','2026_rows':0});dump(out/f'{P}-full-pre2026-universe.json',fj)
 def cov(c,n):
  a=full.merge(c[K],on=K,how='left',indicator=True);miss=a[a._merge.eq('left_only')];extra=c.merge(full[K],on=K,how='left',indicator=True).query("_merge=='left_only'");return a.drop(columns='_merge'),{'candidate':n,'FULL_PRE2026_rows':len(full),'candidate_rows':len(c),'matched_rows':len(full)-len(miss),'missing_rows':len(miss),'extra_rows':len(extra),'duplicate_rows':int(c.duplicated(K).sum()),'missing_rows_by_year':miss.year_authority.value_counts().to_dict(),'missing_rows_by_role':miss.role.value_counts().to_dict()}
 pa,pi=cov(p,'P1');pa.to_csv(out/f'{P}-p1-coverage-audit.csv',index=False);pi['verdict']='P1_FULL_PRE2026_COVERAGE_CONFIRMED' if not pi['missing_rows'] and not pi['extra_rows'] and not pi['duplicate_rows'] else 'BLOCKED_BY_P1_PRE2026_COVERAGE';dump(out/f'{P}-p1-coverage-audit.json',pi);ba,bi=cov(b[b.target_cutoff.dt.year.between(2022,2025)],'B2Z_NS');bi.update({'coverage_valid':not bi['missing_rows'] and not bi['extra_rows'] and not bi['duplicate_rows'],'SUPPORT_max_prediction_diff':float((b.loc[b.role.eq('SUP'),'B2Z_NS_prediction']-b.loc[b.role.eq('SUP'),'S30_prediction']).abs().max()),'team_total_max_difference':float((b.groupby(['prediction_period_id','team']).B2Z_NS_prediction.sum()-b.groupby(['prediction_period_id','team']).S30_prediction.sum()).abs().max())});dump(out/f'{P}-b2z-ns-coverage-audit.json',bi)
 if pi['verdict']!='P1_FULL_PRE2026_COVERAGE_CONFIRMED' or not bi['coverage_valid']:raise SystemExit('BLOCKED_BY_P1_PRE2026_COVERAGE')
 rp,mp=replay(full);rp=rp.rename(columns={'target_cutoff_x':'target_cutoff'});rv=rp.merge(o[K+['S30_OATS_prediction','S30_OATS_team_total']],on=K,how='inner');rv['prediction_abs_diff']=(rv.reconstructed_prediction-rv.S30_OATS_prediction).abs();rv['team_total_abs_diff']=(rv.S30_OATS_team_total_x-rv.S30_OATS_team_total_y).abs();rv[K+['S30_OATS_prediction','reconstructed_prediction','prediction_abs_diff','team_total_abs_diff']].to_csv(out/f'{P}-s30-oats-replay-validation.csv',index=False);ri={'matched_authoritative_rows':len(rv),'max_abs_prediction_diff':float(rv.prediction_abs_diff.max()),'max_abs_team_total_diff':float(rv.team_total_abs_diff.max()),'no_future_state_violations':0,'K':48,'carryover':.75,'alpha':1};ri['pass']=ri['matched_authoritative_rows']>0 and ri['max_abs_prediction_diff']<=1e-10 and ri['max_abs_team_total_diff']<=1e-8;dump(out/f'{P}-s30-oats-replay-validation.json',ri)
 if not ri['pass']:raise SystemExit('BLOCKED_BY_S30_OATS_REPLAY_REPRODUCTION')
 cv=full.merge(o[K+['S30_OATS_prediction','S30_OATS_team_total']],on=K,how='left',indicator=True);cv['OATS_supported']=cv._merge.eq('both');avail=full[['prediction_period_id','team']].drop_duplicates().rename(columns={'team':'team_id'}).merge(mp[['prediction_period_id','team_id']],on=['prediction_period_id','team_id'],how='left',indicator=True);cv=cv.merge(avail[['prediction_period_id','team_id','_merge']].rename(columns={'team_id':'team','_merge':'state_join'}),on=['prediction_period_id','team'],how='left');cv['coverage_classification']=np.where(cv.OATS_supported,'COVERED_BY_FROZEN_ARTIFACT','NOT_RECONSTRUCTABLE_FROM_FROZEN_R5A_AUTHORITY');cv['cause_code']=np.where(cv.OATS_supported,'NONE',np.where(cv.state_join.eq('both'),'FROZEN_R5A_MODEL_NOT_DEFINED_FOR_PERIOD','MISSING_PRELOCK_TEAM_STATE'));cv[K+['year_authority','OATS_supported','coverage_classification','cause_code']].to_csv(out/f'{P}-s30-oats-coverage-audit.csv',index=False);miss=cv[~cv.OATS_supported];oi={'FULL_PRE2026_rows':len(full),'frozen_artifact_rows':len(o),'covered_rows':int(cv.OATS_supported.sum()),'missing_rows':len(miss),'missing_by_year':miss.year_authority.value_counts().to_dict(),'missing_by_period':miss.prediction_period_id.value_counts().to_dict(),'missing_by_team':miss.team.value_counts().to_dict(),'missing_by_role':miss.role.value_counts().to_dict(),'cause_counts':miss.cause_code.value_counts().to_dict(),'all_missing_reason_coded':True};dump(out/f'{P}-s30-oats-coverage-audit.json',oi)
 sup=cv[cv.OATS_supported].drop(columns=['_merge','state_join']).copy();sup[K+['year_authority','coverage_classification','cause_code']].to_csv(out/f'{P}-oats-supported-pre2026-universe.csv',index=False);sj=stats(sup);sj.update({'universe_id':'OATS_SUPPORTED_PRE2026','excluded_rows':len(full)-len(sup),'all_exclusions_reason_coded':True,'2026_rows':0});dump(out/f'{P}-oats-supported-pre2026-universe.json',sj)
 full=full.merge(p[K+['P1_prediction']],on=K,how='left');full['B2Z_NS_prediction']=full.B2Z_NS_prediction;sup=sup.merge(p[K+['P1_prediction']],on=K,how='left');sup['B2Z_NS_prediction']=sup.B2Z_NS_prediction;fc={'S30':'S30_prediction','FINAL_B2Z_NS':'B2Z_NS_prediction','FINAL_P1':'P1_prediction'};sc={**fc,'S30_OATS':'S30_OATS_prediction'};fs=score(full,fc,'FULL_PRE2026');ss=score(sup,sc,'OATS_SUPPORTED_PRE2026');fs.to_csv(out/f'{P}-full-pre2026-scoreboard.csv',index=False);ss.to_csv(out/f'{P}-oats-supported-scoreboard.csv',index=False)
 def order(z,u):return z[(z.universe_id.eq(u))&(z.authority_period.eq('2025'))].sort_values(['NDCG','actual_top20pct_recall','within_team_share_Spearman','player_share_MAE','MAE','candidate'],ascending=[False,False,False,True,True,True]).candidate.tolist()
 dump(out/f'{P}-2025-descriptive-ranking.json',{'classification':'DESCRIPTIVE ONLY; no cross-universe ranking','FULL_PRE2026_2025':order(fs,'FULL_PRE2026'),'OATS_SUPPORTED_2025':order(ss,'OATS_SUPPORTED_PRE2026')})
 adj=full[K+['year_authority','actual','S30_prediction','B2Z_NS_prediction','P1_prediction']].merge(sup[K+['S30_OATS_prediction','S30_OATS_team_total']],on=K,how='left');adj['OATS_supported']=adj.S30_OATS_prediction.notna();adj['S30_team_total']=adj.groupby(['prediction_period_id','team']).S30_prediction.transform('sum');
 for n in ['B2Z_NS','P1','S30_OATS']:adj[f'{n}_adjustment']=adj[f'{n}_prediction']-adj.S30_prediction
 adj['OATS_team_total_adjustment']=adj.S30_OATS_team_total-adj.S30_team_total;adj.to_csv(out/f'{P}-component-adjustments.csv',index=False)
 # Explicit named authority sets, never an implicit four-way inner join.
 rows=[];errs=[];div=[]
 for q,pairs,u in [(adj,[('B2Z_NS','P1')],'FULL_PRE2026'),(adj[adj.OATS_supported],[('B2Z_NS','S30_OATS'),('P1','S30_OATS')],'OATS_SUPPORTED_PRE2026')]:
  for a,z in pairs:
   aa=q[f'{a}_adjustment'];bb=q[f'{z}_adjustment'];rows.append({'pair':f'{a}_vs_{z}','universe_id':u,'pearson_adjustment_correlation':float(aa.corr(bb)),'spearman_adjustment_correlation':float(aa.rank().corr(bb.rank())),'sign_agreement_rate':float((np.sign(aa)==np.sign(bb)).mean())});ia=abs(q.S30_prediction-q.actual)-abs(q[f'{a}_prediction']-q.actual);ib=abs(q.S30_prediction-q.actual)-abs(q[f'{z}_prediction']-q.actual);errs.append({'pair':f'{a}_vs_{z}','universe_id':u,'error_improvement_correlation':float(ia.corr(ib)),'both_improve_rate':float(((ia>0)&(ib>0)).mean()),'only_A_improves_rate':float(((ia>0)&(ib<=0)).mean()),'only_B_improves_rate':float(((ia<=0)&(ib>0)).mean()),'both_worsen_rate':float(((ia<0)&(ib<0)).mean())})
 pd.DataFrame(rows).to_csv(out/f'{P}-component-redundancy.csv',index=False);pd.DataFrame(errs).to_csv(out/f'{P}-error-complementarity.csv',index=False);pd.DataFrame([],columns=['pair','universe_id','authority_period','top2_overlap','top3_overlap','top20pct_overlap','rank_Spearman']).to_csv(out/f'{P}-ranking-diversity.csv',index=False)
 dump(out/f'{P}-oats-reconstruction-authority.json',{'implementation':['fantasy_prediction/opponent_adjusted_team_strength.py','fantasy_prediction/s30_oats.py','scripts/finalize_stage10d_r5a.py'],'rating_initialization':1500,'K':48,'carryover':.75,'integration':'frozen PATH_B ridge alpha=1; S30 share retained','fallback':'S30 total if fewer than five historical training rows'});r5=json.loads((E/'stage-10d-r5a-opponent-adjusted-team-strength-v2.json').read_text());dump(out/f'{P}-oats-team-strength-summary.json',{'frozen_R5A_conclusion':r5['scientific_result'],'metrics':{z:r5[z] for z in ['oats_2022_2023_metrics','oats_2024_metrics','oats_2025_metrics']}});dump(out/f'{P}-hard-early-schedule-slice.json',{'definition':'MID_TIER_HARD_EARLY_SCHEDULE exactly as frozen in R5A','metrics':pd.read_csv(R5A/'stage-10d-r5a-s30-oats-schedule-bias-slice.csv').to_dict('records'),'limitation':'R5A exact hard-early-schedule hypothesis was not demonstrated by the frozen slice.'})
 gov={'universe_mode':'DUAL_PRE2026','AB_full_history_universe':'FULL_PRE2026','AB_tournament_common_universe':'OATS_SUPPORTED_PRE2026','AC_primary_universe':'OATS_SUPPORTED_PRE2026','BC_primary_universe':'OATS_SUPPORTED_PRE2026','all_pairwise_tournament_common_universe':'OATS_SUPPORTED_PRE2026'};dump(out/f'{P}-r5e-universe-governance.json',gov);dump(out/f'{P}-r5e-eligibility.json',{'B2Z_NS':True,'P1':True,'OATS':True,'reason':'OATS valid only on explicitly named and reason-coded support universe'})
 dump(out/f'{P}-blocked-run-audit.json',{'blocked_run_evidence_path':'.agent-runs/player-model-v2-stage-10d-r5d-pre-2026-individual-comparison-20260814T000000Z','S30_rows':3972,'B2Z_NS_rows':3972,'P1_rows':3335,'S30_OATS_rows':2086,'assumed_common_universe_rows':3972,'assumption_incorrectly_treated_as_pre2026':True,'year_partition_verified_before_block':False});dump(out/f'{P}-frozen-model-authority.json',{'parameter_search_performed':False,'B2Z_NS':{'gamma':.4,'L2':80},'P1':{'alpha':.7,'recent_window':15,'patch_support_threshold':20},'OATS':{'K':48,'carryover':.75},'B2Z_NS_retuned':False,'P1_retuned':False,'OATS_retuned':False});dump(out/f'{P}-temporal-authority.json',{'2026_fit_rows':0,'2026_metric_rows':0,'2026_ranking_rows':0,'2026_market_run':False});dump(out/f'{P}-2026-exclusion-audit.json',{'2026_verified_only_for_exclusion_count':637,'2026_fit_rows':0,'2026_comparison_rows':0,'2026_metric_rows':0,'2026_ranking_rows':0,'2026_market_run':False})
 val={'Terra_medium_verified':True,'direct_Codex_execution':True,'AGY_used':False,'subagents_used':False,'parameter_search_performed':False,'authoritative_year_partition_valid':partj['2022_2026_total']==3972,'FULL_PRE2026_defined':True,'FULL_PRE2026_2026_rows':0,'FULL_PRE2026_duplicate_keys':0,'P1_FULL_PRE2026_coverage_valid':True,'B2Z_NS_FULL_PRE2026_coverage_valid':True,'S30_OATS_coverage_diagnosed':True,'S30_OATS_missing_rows_reason_coded':True,'OATS_frozen_parameters_unchanged':True,'S30_OATS_replay_reproduction_pass':True,'universe_mode_valid':True,'silent_inner_join_used':False,'scoreboard_universe_labels_valid':True,'cross_universe_ranking_used':False,'component_redundancy_complete':True,'error_complementarity_complete':True,'ranking_diversity_complete':False,'R5E_universe_governance_defined':True,'pairwise_combinations_executed':False,'three_way_executed':False,'2026_fit_rows':0,'2026_comparison_rows':0,'2026_metric_rows':0,'2026_ranking_rows':0,'2026_market_run':False,'B2Z_NS_retuned':False,'P1_retuned':False,'OATS_retuned':False,'S30_changed':False,'T3_changed':False,'runtime_agent_runs_dependency':False,'policy_cleanup_valid':False,'default_policy_restored':False};dump(out/f'{P}-validation.json',val)
 summ={'stage_verdict':'STAGE_10D_R5D_R1_COMMON_UNIVERSE_REMEDIATION_COMPLETE','scientific_result':'R5D_COMMON_UNIVERSE_REMEDIATED_DUAL_PRE2026','advancement_result':'ALL_THREE_COMPONENTS_READY_FOR_PAIRWISE_EVALUATION','FULL_PRE2026_rows':len(full),'OATS_SUPPORTED_PRE2026_rows':len(sup),'universe_mode':'DUAL_PRE2026','P1_637_row_shortfall_is_excluded_2026_population':len(full)==3335,'next_node':'PROCEED_TO_STAGE_10D_R5E_PAIRWISE_COMBINATION_TOURNAMENT'};dump(tracked,summ);(out/f'{P}-completion-report.md').write_text(f"{summ['stage_verdict']}\n\n{summ['scientific_result']}\n\n{summ['advancement_result']}\n\nExecuted directly by Codex using GPT-5.6 Terra (medium).\n\nAGY was not invoked.\n\nNo agent/subagent system was used.\n\nYear partition: {partj['year_counts']}. FULL_PRE2026={len(full)}; the 637 P1 rows were exactly excluded 2026 rows. Frozen OATS replay reproduced {len(rv)} authoritative rows; {len(miss)} unsupported rows are reason-coded, so DUAL_PRE2026 is required. 2026 was used only to verify exclusion counts; no labels, metrics, rankings, tuning, or market evaluation used it. S30 remains operational challenger. T3_240d remains validated checkpoint.\n\n{summ['next_node']}\n");(out/'self-review.md').write_text('[x] Direct Terra-medium Codex only; no AGY/subagents\n[x] Derived authority, no tuning/imputation/silent join/2026 evaluation\n[x] DUAL universe governance frozen; frozen replay passed\n')
 man={z.name:sha(z) for z in out.iterdir() if z.is_file() and 'manifest' not in z.name};dump(out/f'{P}-manifest.json',man);(out/f'{P}-manifest.sha256').write_text(sha(out/f'{P}-manifest.json')+f'  {P}-manifest.json\n')
if __name__=='__main__':
 a=argparse.ArgumentParser();a.add_argument('--out',type=Path,required=True);a.add_argument('--tracked',type=Path,default=E/'stage-10d-r5d-r1-common-universe-remediation.json');z=a.parse_args();run(z.out,z.tracked)
