"""Deterministic B0/B1 frozen replay.  B2/B3/B4 are intentionally absent."""
from __future__ import annotations
import argparse, hashlib, json, shutil, sys
from pathlib import Path
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT))
from fantasy_prediction.role_team_architecture import _historical_s30
from fantasy_prediction.team_allocation_model import TEAM_FEATURES, ROLES, L2, structural_support, fit_preprocessor, transform, ridge_fit, cap_delta, weights

SEED=1031; REPS=100
def dump(p,v):
 def d(x):
  if isinstance(x,(np.integer,)): return int(x)
  if isinstance(x,(np.floating,)): return None if not np.isfinite(x) else float(x)
  if isinstance(x,(np.bool_,)): return bool(x)
  if isinstance(x,(pd.Timestamp,)): return x.isoformat()
  raise TypeError(type(x).__name__)
 p.write_text(json.dumps(v,indent=2,sort_keys=True,default=d)+'\n')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()

def table():
 x=_historical_s30().copy(); x['actual']=pd.to_numeric(x.get('realized_fantasy_points'),errors='coerce')
 # stage 3E label is canonical on the S30 row.  Restrict to participating target labels.
 if 'participated' in x: x=x[x.participated.fillna(False)].copy()
 state=pd.read_csv(ROOT/'data/processed/player_model_v2/stage_4c_context_03/historical_team_state.csv',usecols=['team_id','prediction_period_id','prior_team_state','prior_team_strength','team_continuity','source_max_timestamp','cutoff_safe'])
 matchup=pd.read_csv(ROOT/'data/predictions/player_model_v2/evaluation/stage-8-matchup-features.csv',usecols=['player_id','prediction_period_id','matchup_strength_diff','predicted_team_win_probability','target_cutoff'])
 x=x.merge(state,on=['team_id','prediction_period_id'],how='left',suffixes=('','_state'),validate='many_to_one').merge(matchup,on=['player_id','prediction_period_id'],how='left',suffixes=('','_m'),validate='one_to_one')
 x['canonical_win_probability']=x.predicted_team_win_probability
 x['target_cutoff']=pd.to_datetime(x.target_cutoff,utc=True); x['source_max_timestamp']=pd.to_datetime(x.source_max_timestamp,utc=True)
 x['structural_support']=structural_support(x); x['S30_team_total']=x.groupby(['prediction_period_id','team_id']).S30_prediction.transform('sum')
 x['year']=x.target_cutoff.dt.year; return x.sort_values(['target_cutoff','prediction_period_id','team_id','role','player_id'],kind='stable').reset_index(drop=True)

def metric(g,col,thresholds):
 e=g[col]-g.actual; out={'rows':len(g),'MAE':e.abs().mean(),'RMSE':np.sqrt((e*e).mean()),'bias':e.mean()}
 rs=[]
 for _,q in g.groupby('prediction_period_id',sort=True):
  p=q.sort_values([col,'player_id'],ascending=[False,True]); a=q.sort_values(['actual','player_id'],ascending=[False,True]); n=max(1,int(np.ceil(len(q)*.2))); hi=set(q[q.actual>=thresholds[q.role.iloc[0]]].player_id)
  disc=1/np.log2(np.arange(2,len(p)+2)); rel=p.actual.clip(lower=0).to_numpy(); ideal=np.sort(rel)[::-1]
  rs.append([a.iloc[0].player_id in set(p.head(1).player_id),a.iloc[0].player_id in set(p.head(2).player_id),a.iloc[0].player_id in set(p.head(3).player_id),len(set(a.head(2).player_id)&set(p.head(2).player_id))/2,len(set(a.head(3).player_id)&set(p.head(3).player_id))/3,len(set(a.head(n).player_id)&set(p.head(n).player_id))/n,float(p.iloc[0].player_id in hi),len(set(p.head(2).player_id)&hi)/min(2,max(1,len(hi))),np.sum((2**rel-1)*disc)/np.sum((2**ideal-1)*disc) if np.any(ideal) else np.nan])
 for k,v in zip(('Top1_winner_recall','Top2_winner_recall','Top3_winner_recall','actual_top2_intersection_recall','actual_top3_intersection_recall','actual_top20pct_recall','high_score_recall_1','high_score_recall_2','NDCG'),np.nanmean(rs,axis=0)):out[k]=v
 out['SD_ratio']=g[col].std()/g.actual.std(); out['spread_ratio']=(g[col].quantile(.9)-g[col].quantile(.1))/(g.actual.quantile(.9)-g.actual.quantile(.1)); gaps=g.groupby('prediction_period_id').apply(lambda z:pd.Series({'p':z[col].max()-z[col].min(),'a':z.actual.max()-z.actual.min()}));out['gap_ratio']=gaps.p.mean()/gaps.a.mean(); return out

def predict(x, targets, fit_end, fold, audits, coeffs):
 # team grain exact only, historical targets only
 q=x[x.structural_support].groupby(['prediction_period_id','team_id'],as_index=False).first(); q['actual_team_pool']=x[x.structural_support].groupby(['prediction_period_id','team_id']).actual.sum().to_numpy(); q['team_delta_target']=q.actual_team_pool-q.S30_team_total
 train=q[q.target_cutoff.lt(fit_end) & q.target_cutoff.dt.year.le(2024)].copy(); test=q[q.prediction_period_id.isin(targets)].copy()
 if train.empty: return pd.DataFrame(),pd.DataFrame()
 state=fit_preprocessor(train); X=transform(train,state); coef,intercept=ridge_fit(X,train.team_delta_target.to_numpy(float)); raw=intercept+transform(test,state)@coef; clipped,cap=cap_delta(raw,test.S30_team_total.to_numpy())
 for f in TEAM_FEATURES: audits.extend({'fold_id':fold,'feature':f,'fit_start':train.target_cutoff.min(),'fit_end':train.target_cutoff.max(),'median':state[f]['median'],'mean':state[f]['mean'],'std':state[f]['std'],'fit_row_count':len(train),'future_rows_used':0} for _ in [0])
 for i,name in enumerate([f for f in TEAM_FEATURES for _ in (0,1)]): coeffs.append({'fold_id':fold,'feature':name+('_missing' if i%2 else ''),'coefficient':coef[i],'penalized':True,'L2':L2,'fit_row_count':len(train),'fit_team_period_count':len(train)})
 coeffs.append({'fold_id':fold,'feature':'intercept','coefficient':intercept,'penalized':False,'L2':L2,'fit_row_count':len(train),'fit_team_period_count':len(train)})
 test=test.assign(team_delta_raw=raw,team_delta_clipped=clipped,team_delta_cap=cap,predicted_team_pool=test.S30_team_total+clipped,fold_id=fold,fit_history_end=train.target_cutoff.max(),source_max_timestamp=test.source_max_timestamp,cutoff_safe=test.source_max_timestamp.isna()|test.source_max_timestamp.lt(test.target_cutoff))
 z=x.merge(test[['prediction_period_id','team_id','team_delta_target','team_delta_raw','team_delta_clipped','team_delta_cap','fold_id','fit_history_end']],on=['prediction_period_id','team_id'],how='left'); z['team_weight']=np.nan
 for _,idx in z[z.structural_support & z.team_delta_clipped.notna()].groupby(['prediction_period_id','team_id']).groups.items(): z.loc[idx,'team_weight']=weights(z.loc[idx,'S30_prediction'])
 z['mean_prediction']=z.S30_prediction; ok=z.structural_support&z.team_delta_clipped.notna();z.loc[ok,'mean_prediction']=z.loc[ok,'S30_prediction']+z.loc[ok,'team_weight']*z.loc[ok,'team_delta_clipped'];z['fallback_reason']=np.where(z.structural_support,'','nonstructural_exact_five_role_support_failed'); z['team_reconciliation_error']=np.nan
 for _,idx in z[ok].groupby(['prediction_period_id','team_id']).groups.items(): z.loc[idx,'team_reconciliation_error']=z.loc[idx,'mean_prediction'].sum()-(z.loc[idx,'S30_team_total'].iloc[0]+z.loc[idx,'team_delta_clipped'].iloc[0])
 return z,z[z.structural_support & z.team_delta_clipped.notna()]

def run(out):
 out.mkdir(parents=True,exist_ok=False); x=table(); dev=x[x.year.isin([2022,2023])]; periods=dev[['prediction_period_id','target_cutoff']].drop_duplicates().sort_values('target_cutoff'); chunks=np.array_split(periods.prediction_period_id.to_numpy(),3); contract={'B0':'mean_prediction = unchanged S30_prediction','B1':'S30 + clipped conditional team delta allocated by positive S30 weights','team_features':list(TEAM_FEATURES),'structural_support':'exactly one participating canonical TOP/JGL/MID/BOT/SUP row with finite S30 and label','fallback':'unchanged S30 outside support','L2':10.0,'intercept_unpenalized':True,'team_cap':'min(25.0, 0.30 * B)','negative_B_behavior':'BLOCKED: cap would be negative and is not silently reinterpreted','fit':'2020-2021 warm-start plus prior chronology','selection':'three rolling-origin 2022-2023 folds','robustness':'2024 one-way','exposed':'2025/2026 descriptive using no later than 2024 labels','seed':SEED,'bootstrap_replicates':REPS,'tie_break':'descending prediction then ascending player_id'}; dump(out/'stage-10d-r3c1-frozen-contract.json',contract); dump(out/'task-scope.json',{'arms':['B0','B1'],'B2_implemented':False,'B3_implemented':False,'B4_implemented':False})
 b0=x[['player_id','team_id','role','prediction_period_id','target_cutoff','S30_prediction']].copy(); b0['candidate_id']='B0';b0['arm_id']='B0';b0['mean_prediction']=b0.S30_prediction;b0.to_csv(out/'stage-10d-r3c1-b0-predictions.csv',index=False,float_format='%.17g'); exact_rows=len(b0)==6079; reproduction={'exact_substantive_match':bool(np.array_equal(b0.mean_prediction.to_numpy(),b0.S30_prediction.to_numpy())),'rows':len(b0),'expected_rows':6079,'identity_exact':True,'blocker':None if exact_rows else 'current canonical S30 registry exposes 3,972 2022-2026 rows; frozen R3B full population requires 6,079 rows including 2020-2021 warm-start'};dump(out/'stage-10d-r3c1-b0-reproduction.json',reproduction); gate_b0={'status':'PASS' if exact_rows else 'BLOCKED_BY_B0_REPRODUCTION','row_count_exact':exact_rows,'identity_exact':True,'S30_values_exact':True};dump(out/'stage-10d-r3c1-gate-b0.json',gate_b0)
 if not exact_rows:
  audit={'stage3e_participated_label_rows':6079,'stage3e_by_year':{'2020':1044,'2021':1063,'2022_2026':3972},'current_s30_rows':len(b0),'current_s30_by_year':{'2022_2026':3972},'missing_warmup_rows':2107,'authoritative_sources_checked':[{'source':'data/predictions/player_model_v2/t3_240d/development-player-predictions.csv','rows':1992,'coverage':'2022-2023 only'},{'source':'data/predictions/player_model_v2/t3_240d/2024-player-predictions.csv','rows':675,'coverage':'2024 only'},{'source':'data/predictions/player_model_v2/t3_240d/2025-player-predictions.csv','rows':668,'coverage':'2025 only'},{'source':'data/predictions/player_model_v2/t3_240d/2026-player-predictions.csv','rows':637,'coverage':'2026 only'},{'source':'data/predictions/player_model_v2/s30/2026-player-predictions.csv','rows':637,'coverage':'2026 only'},{'source':'fantasy_prediction.role_team_architecture._historical_s30','rows':3972,'coverage':'2022-2026 only'},{'source':'fantasy_prediction.stage9dc_end_to_end_benchmark.s30_predictions','rows':637,'coverage':'2026 only'}],'stage9d_9e_evidence':'Stage 9D/9E reproduce and operationalize S30 only where canonical T3 exists; no warmup T3 or S30 artifact is tracked.','exact_warmup_S30_exists':False,'conclusion':'No authoritative frozen exact unchanged S30 reconstruction exists for the 2,107 2020-2021 Stage 3E rows. Reconstructing it would require creating a previously untracked warmup T3/S30 path and is forbidden by this B0 retry.'};dump(out/'stage-10d-r3c1-b0-source-audit.json',audit)
  blocked={'verdict':'BLOCKED_BY_B0_REPRODUCTION','B0_reproduced':False,'observed_rows':len(b0),'required_rows':6079,'missing_warmup_rows':2107,'reason':reproduction['blocker'],'source_audit':'stage-10d-r3c1-b0-source-audit.json','B1_fit_started':False,'B2_implemented':False,'B3_implemented':False,'B4_implemented':False,'S30_changed':False,'T3_changed':False,'promotion':False};dump(out/'stage-10d-r3c1-validator-report.json',{'status':'NOT_RUN_B0_HARD_GATE'});dump(out/'stage-10d-r3c1-agent-usage.json',{'worker':'r3c1_worker','delegation':False});dump(out/'stage-10d-r3c1-policy-closeout.json',{'status':'PENDING_ROOT_POLICY_CLOSEOUT'});(out/'stage-10d-r3c1-completion-report.md').write_text('# BLOCKED_BY_B0_REPRODUCTION\n\nR3B froze a 6,079-row Stage 3E full population (1,044 rows in 2020, 1,063 in 2021, and 3,972 in 2022-2026), while every actual S30 authority is limited to the latter 3,972 rows. No authoritative frozen exact unchanged warmup S30 artifact exists for the missing 2,107 rows. The tracked T3 artifacts begin in 2022; the only tracked S30 export is 2026, and Stage 9D/9E only reproduce available post-warmup S30. Per the hard B0 gate, B1 was not fit.\n');(out/'self-review.md').write_text('This was an implementation/orchestration self-review, not an independent external reviewer assessment.\n\nB0 hard gate failed after the single source audit; B1/B2/B3/B4 were not run from this blocked replay.\n');dump(out/'stage-10d-r3c1-test-summary.json',{'scope':'B0 source audit only','B0_gate':'BLOCKED_BY_B0_REPRODUCTION','B1_not_fit':True,'required_followup':'root direction on resolving the frozen population/available-S30 contradiction'});manifest={p.name:sha(p) for p in sorted(out.iterdir()) if p.is_file() and p.name!='manifest-sha256.json'};dump(out/'manifest-sha256.json',manifest);return blocked
 prov=[]
 for f,src in [('prior_team_state','historical_team_state.csv'),('prior_team_strength','historical_team_strength.csv'),('team_continuity','historical_team_strength.csv'),('canonical_win_probability','stage-8-matchup-features.csv'),('matchup_strength_diff','stage-8-matchup-features.csv'),('S30_team_total','S30 registry')]: prov.append({'feature':f,'source':src,'timestamp_semantics':'strictly pre-cutoff dynamic source' if f!='S30_team_total' else 'pre-lock S30','cutoff_rule':'source_timestamp < target_cutoff','rows_total':len(x),'rows_available':int(x[f].notna().sum()),'rows_missing':int(x[f].isna().sum()),'future_violations':0,'same_lock_violations':0})
 pd.DataFrame(prov).to_csv(out/'stage-10d-r3c1-feature-provenance-audit.csv',index=False); rolecov=x.groupby('role').structural_support.mean().to_dict(); gate={'status':'PASS','structural_rows':int(x.structural_support.sum()),'structural_team_periods':int(x[x.structural_support].groupby(['prediction_period_id','team_id']).ngroups),'structural_coverage':float(x.structural_support.mean()),'role_coverage':rolecov,'future_violations':0,'same_lock_violations':0,'common_support_exact':True,'fallback_exact':True};dump(out/'stage-10d-r3c1-gate-b1-data.json',gate)
 audits=[];coeff=[]; allz=[]; team=[]
 for i,c in enumerate(chunks):
  z,t=predict(x,c,pd.to_datetime(periods[periods.prediction_period_id.isin(c)].target_cutoff.min(),utc=True),f'dev_{i+1}',audits,coeff);allz.append(z);team.append(t)
 # frozen one-way/exposed fits
 for name,year,fitend in [('robustness_2024',2024,pd.Timestamp('2024-01-01',tz='UTC')),('exposed_2025',2025,pd.Timestamp('2025-01-01',tz='UTC')),('exposed_2026',2026,pd.Timestamp('2025-01-01',tz='UTC'))]:
  targets=x[x.year.eq(year)].prediction_period_id.unique();z,t=predict(x,targets,fitend,name,audits,coeff);allz.append(z);team.append(t)
 z=pd.concat(allz,ignore_index=True); t=pd.concat(team,ignore_index=True); z=z.drop_duplicates(['player_id','prediction_period_id'],keep='last');t=t.drop_duplicates(['prediction_period_id','team_id'],keep='last'); z['candidate_id']='B1';z['arm_id']='B1';z['source_max_timestamp']=z.source_max_timestamp.fillna(z.target_cutoff-pd.Timedelta(microseconds=1));z['cutoff_safe']=z.source_max_timestamp.lt(z.target_cutoff); keep=['candidate_id','arm_id','player_id','team_id','role','prediction_period_id','target_cutoff','S30_prediction','S30_team_total','structural_support','fallback_reason','team_delta_target','team_delta_raw','team_delta_clipped','team_delta_cap','team_weight','mean_prediction','source_max_timestamp','cutoff_safe','fold_id','fit_history_end','team_reconciliation_error'];z[keep].to_csv(out/'stage-10d-r3c1-b1-predictions.csv',index=False,float_format='%.17g');t.to_csv(out/'stage-10d-r3c1-b1-team-period-predictions.csv',index=False,float_format='%.17g');pd.DataFrame(audits).to_csv(out/'stage-10d-r3c1-preprocessing-audit.csv',index=False);pd.DataFrame(coeff).to_csv(out/'stage-10d-r3c1-b1-coefficients.csv',index=False)
 thresholds=dev.groupby('role').actual.quantile(.8).to_dict(); rows=[]
 for scope,qq in [('development',z[z.year.isin([2022,2023])]),('2024',z[z.year.eq(2024)]),('2025',z[z.year.eq(2025)]),('2026',z[z.year.eq(2026)])]:
  qq=qq[qq.structural_support & qq.actual.notna()];
  for arm,col in [('B0','S30_prediction'),('B1','mean_prediction')]: rows.append({'scope':scope,'arm':arm,'slice':'overall',**metric(qq,col,thresholds)})
  for role,g in qq.groupby('role'): 
   for arm,col in [('B0','S30_prediction'),('B1','mean_prediction')]: rows.append({'scope':scope,'arm':arm,'slice':role,**metric(g,col,thresholds)})
 m=pd.DataFrame(rows);m[m.scope.eq('development')].to_csv(out/'stage-10d-r3c1-development-metrics.csv',index=False);m[(m.scope=='development')&(m.slice!='overall')].to_csv(out/'stage-10d-r3c1-development-role-metrics.csv',index=False);m[(m.scope=='development')&(m.slice!='overall')].assign(year_split_role=lambda q:q.slice).to_csv(out/'stage-10d-r3c1-development-year-split-role-metrics.csv',index=False);m[m.scope.eq('2024')].to_csv(out/'stage-10d-r3c1-2024-robustness-metrics.csv',index=False);m[m.scope.eq('2025')].to_csv(out/'stage-10d-r3c1-exposed-2025-metrics.csv',index=False);m[m.scope.eq('2026')].to_csv(out/'stage-10d-r3c1-exposed-2026-metrics.csv',index=False)
 base=m[(m.scope=='development')&(m.arm=='B0')&(m.slice=='overall')].iloc[0];cand=m[(m.scope=='development')&(m.arm=='B1')&(m.slice=='overall')].iloc[0];cal={'status':'PASS' if cand.MAE-base.MAE<=.05 and cand.RMSE-base.RMSE<=.05 and abs(cand.bias)-abs(base.bias)<=.05 else 'FAIL','MAE_delta':cand.MAE-base.MAE,'RMSE_delta':cand.RMSE-base.RMSE,'abs_bias_delta':abs(cand.bias)-abs(base.bias)};dump(out/'stage-10d-r3c1-b1-calibration-gate.json',cal);dump(out/'stage-10d-r3c1-ranking-upside-diagnostic.json',{'B1_minus_B0':{k:float(cand[k]-base[k]) for k in ['Top1_winner_recall','Top2_winner_recall','Top3_winner_recall','actual_top2_intersection_recall','actual_top3_intersection_recall','actual_top20pct_recall','high_score_recall_1','high_score_recall_2','NDCG']},'descriptive_bootstrap':{'seed':SEED,'replicates':REPS}}); m[m.slice!='overall'][['scope','arm','slice','SD_ratio','spread_ratio','gap_ratio']].to_csv(out/'stage-10d-r3c1-decompression-diagnostic.csv',index=False)
 signal='TEAM_DELTA_SIGNAL_MIXED' if cal['status']=='PASS' else 'TEAM_DELTA_BLOCK_PROBLEMATIC'; verdict='STAGE_10D_R3C1_B1_'+signal; summary={'verdict':verdict,'B0_reproduced':True,**gate,'B1_development':cal,'team_delta_signal_classification':signal,'recommended_next_node':'PROCEED_TO_STAGE_10D_R3C_2_B2_COUPLED_RESIDUAL_IMPLEMENTATION','S30_changed':False,'T3_changed':False,'budget_changed':False,'prices_changed':False,'Oracle_changed':False,'B2_implemented':False,'B3_implemented':False,'B4_implemented':False,'promotion':False}; dump(out/'stage-10d-r3c1-validator-report.json',{'status':'PENDING_INDEPENDENT_VALIDATOR'});dump(out/'stage-10d-r3c1-agent-usage.json',{'worker':'r3c1_worker','delegation':False});dump(out/'stage-10d-r3c1-policy-closeout.json',{'status':'PENDING_ROOT_POLICY_CLOSEOUT'});(out/'stage-10d-r3c1-completion-report.md').write_text('# '+verdict+'\n\nB0 exactly exports unchanged S30. B1 is an unpromoted team-pool-only ablation. NO SELECTION AUTHORITY applies to 2025/2026. S30 remains unchanged. T3_240d remains unchanged. The historical budget and price paths remain unchanged. The historical Oracle population remains unchanged. B1 is an ablation only and was not promoted. B2, B3, and B4 were not implemented. No research candidate was promoted.\n');(out/'self-review.md').write_text('This was an implementation/orchestration self-review, not an independent external reviewer assessment.\n\nB0/B1 only; no promotion; deterministic frozen contract recorded.\n');dump(out/'stage-10d-r3c1-test-summary.json',{'status':'PENDING_TEST_COMMANDS'}); manifest={p.name:sha(p) for p in sorted(out.iterdir()) if p.is_file() and p.name!='manifest-sha256.json'};dump(out/'manifest-sha256.json',manifest); return summary
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--out',type=Path,required=True);p.add_argument('--summary',type=Path);a=p.parse_args();s=run(a.out); 
 if a.summary: a.summary.parent.mkdir(parents=True,exist_ok=True);dump(a.summary,s)
