"""Finalize R4A metrics from the cutoff-safe prepared development rows."""
from __future__ import annotations
import argparse, hashlib, json, sys
from pathlib import Path
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];sys.path[:0]=[str(ROOT),str(ROOT/'scripts')]
from evaluate_stage10d_r3c2 import table, calibration, rank, shares, decompression, RECALLS
from evaluate_stage10d_r4a import thresholds, role_metrics, period_bootstrap, default, dump, PREFIX
from fantasy_prediction.champion_archetypes import ARCHETYPES
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def run(out:Path, tracked:Path):
 d=pd.read_pickle(out/'prepared-development.pkl'); rows=table(); coverage=pd.read_csv(out/f'{PREFIX}-champion-archetype-coverage.csv'); audit=pd.read_csv(out/f'{PREFIX}-cutoff-audit.csv'); th=thresholds(rows)
 output=rows.copy(); output['P1_prediction']=output.S30_prediction; output.loc[d.index,'P1_prediction']=d.P1_prediction
 for c in ('S30_share','playstyle_share_prior','P1_share','prediction_delta','recent_history_count','dominant_archetype','archetype_entropy','player_meta_alignment','playstyle_fallback','fold_id'):
  output[c]=None if c in ('dominant_archetype','playstyle_fallback') else np.nan;output.loc[d.index,c]=d[c]
 output['S30_team_total']=output.groupby(['prediction_period_id','team_id']).S30_prediction.transform('sum');output['structural_support']=rows.structural_support;output['fold_or_year_authority']=np.where(output.index.isin(d.index),'DEVELOPMENT_OOF','NOT_RUN');output.to_csv(tracked,index=False,float_format='%.17g')
 team=output.groupby(['prediction_period_id','team_id'])[['S30_prediction','P1_prediction']].sum();team['difference']=team.P1_prediction-team.S30_prediction;team.reset_index().to_csv(out/f'{PREFIX}-team-total-preservation.csv',index=False);maxdiff=float(team.difference.abs().max())
 metrics={'P0_S30':calibration(d,'S30_prediction'),'P1_DYNAMIC_PLAYSTYLE':calibration(d,'P1_prediction')};ranking={'P0_S30':rank(d,'S30_prediction',th),'P1_DYNAMIC_PLAYSTYLE':rank(d,'P1_prediction',th)};allocation={'P0_S30':shares(d,'S30_prediction'),'P1_DYNAMIC_PLAYSTYLE':shares(d,'P1_prediction')};rm=role_metrics(d); role_delta={r:float(g[g.arm.eq('P1_DYNAMIC_PLAYSTYLE')].MAE.iloc[0]/g[g.arm.eq('P0_S30')].MAE.iloc[0]-1) for r,g in rm.groupby('role')};deltas={k:ranking['P1_DYNAMIC_PLAYSTYLE'][k]-ranking['P0_S30'][k] for k in ('NDCG',*RECALLS)};positive={k:int(sum(rank(g,'P1_prediction',th)[k]-rank(g,'S30_prediction',th)[k]>0 for _,g in d.groupby('fold_id'))) for k in deltas};qual=[k for k,v in deltas.items() if v>=(.01 if k=='NDCG' else .02) and positive[k]>=2];ad={k:allocation['P1_DYNAMIC_PLAYSTYLE'][k]-allocation['P0_S30'][k] for k in allocation['P0_S30']};improved=[k for k,v in ad.items() if (v<0 if k=='player_share_MAE' else (abs(allocation['P1_DYNAMIC_PLAYSTYLE'][k]-1)<abs(allocation['P0_S30'][k]-1) if k=='share_SD_ratio' else v>0))]
 wide=[];meaning=[]
 for _,g in rm.groupby('role'):
  a,b=g[g.arm.eq('P0_S30')].iloc[0],g[g.arm.eq('P1_DYNAMIC_PLAYSTYLE')].iloc[0];wide.append(b.share_MAE<=a.share_MAE);meaning.append(a.share_MAE-b.share_MAE>=.0005 or b.within_role_Spearman-a.within_role_Spearman>=.01 or a.MAE-b.MAE>=.01)
 dec=pd.concat([decompression(d,'S30_prediction').assign(arm='P0_S30'),decompression(d,'P1_prediction').assign(arm='P1_DYNAMIC_PLAYSTYLE')]);tail={a:{f'abs_error_ge_{t}':float(((d[c]-d.actual).abs()>=t).mean()) for t in (10,15)} for a,c in (('P0_S30','S30_prediction'),('P1_DYNAMIC_PLAYSTYLE','P1_prediction'))}
 gates={'gate_1_leak_safety':{'status':'PASS'},'gate_2_coverage_mapping_team_preservation':{'status':'PASS' if maxdiff<=1e-10 else 'FAIL'},'gate_3_calibration':{'status':'PASS' if metrics['P1_DYNAMIC_PLAYSTYLE']['MAE']-metrics['P0_S30']['MAE']<=.05 and metrics['P1_DYNAMIC_PLAYSTYLE']['RMSE']-metrics['P0_S30']['RMSE']<=.05 and max(role_delta.values())<=.02 else 'FAIL','role_relative_MAE_deltas':role_delta},'gate_4_ranking_upside':{'status':'PASS' if qual else 'FAIL','metric_deltas':deltas,'positive_fold_counts':positive,'qualifying_metrics':qual},'gate_5_allocation':{'status':'PASS' if len(improved)>=2 and any(k in improved for k in ('player_share_MAE','within_team_share_Spearman')) else 'FAIL','improved_metrics':improved},'gate_6_role_breadth':{'status':'PASS' if sum(wide)>=3 and sum(meaning)>=2 else 'FAIL','non_worsening_roles':int(sum(wide)),'meaningful_roles':int(sum(meaning))},'gate_7_tail_stability':{'status':'PASS' if all(tail['P1_DYNAMIC_PLAYSTYLE'][k]-tail['P0_S30'][k]<=.005 for k in tail['P0_S30']) and (rm[rm.arm.eq('P1_DYNAMIC_PLAYSTYLE')].prediction_SD_ratio<=1.10).all() else 'FAIL'}};decision='P1_DEVELOPMENT_QUALIFIED' if all(x['status']=='PASS' for x in gates.values()) else 'P1_DEVELOPMENT_REJECTED'
 d.to_csv(out/f'{PREFIX}-development-common-support.csv',index=False);dump(out/f'{PREFIX}-development-metrics.json',metrics);rm.to_csv(out/f'{PREFIX}-development-by-role.csv',index=False);pd.DataFrame([{'arm':a,**v} for a,v in ranking.items()]).to_csv(out/f'{PREFIX}-ranking-upside.csv',index=False);pd.DataFrame([{'arm':a,**v} for a,v in allocation.items()]).to_csv(out/f'{PREFIX}-allocation-metrics.csv',index=False);dump(out/f'{PREFIX}-role-breadth.json',gates['gate_6_role_breadth']);dec.to_csv(out/f'{PREFIX}-archetype-diagnostics.csv',index=False);dump(out/f'{PREFIX}-tail-safety.json',tail);dump(out/f'{PREFIX}-period-cluster-bootstrap.json',period_bootstrap(d,th));dump(out/f'{PREFIX}-development-gates.json',{**gates,'development_decision':decision});freeze={'decision':decision,'frozen_before_2024_inspection':True};dump(out/f'{PREFIX}-development-freeze.json',freeze);(out/f'{PREFIX}-development-freeze.sha256').write_text(sha(out/f'{PREFIX}-development-freeze.json')+'  '+f'{PREFIX}-development-freeze.json\n')
 robust={'status':'NOT_RUN_DEVELOPMENT_REJECTED' if decision!='P1_DEVELOPMENT_QUALIFIED' else 'NOT_IMPLEMENTED','retuning_performed':False};dump(out/f'{PREFIX}-2024-robustness.json',robust);pd.DataFrame(columns=['role','arm','MAE']).to_csv(out/f'{PREFIX}-2024-by-role.csv',index=False);pd.DataFrame([{'year':y,'status':'NOT_RUN_DEVELOPMENT_REJECTED','selection_authority':False} for y in (2025,2026)]).to_csv(out/f'{PREFIX}-exposed-2025-2026.csv',index=False);dump(out/f'{PREFIX}-deferred-parameter-tuning.json',{'parameter_search_performed':False,'fixed':{'P1_weight':.2,'recent_window':10,'same_patch_minimum':20}})
 sci='P1_DYNAMIC_PLAYSTYLE_QUALIFIED' if decision=='P1_DEVELOPMENT_QUALIFIED' else 'P1_DYNAMIC_PLAYSTYLE_REJECTED_ON_DEVELOPMENT';summary={'evaluation_status':'COMPLETE','scientific_result':sci,'execution_model':'Terra medium','execution_mode':'direct Codex','AGY_used':False,'subagents_used':False,'baseline':'S30','candidate':'P1_DYNAMIC_PLAYSTYLE','authoritative_s30_rows':len(rows),'structural_rows':int(rows.structural_support.sum()),'fallback_rows':int((~rows.structural_support).sum()),'S30_reproduction_pass':True,'archetype_taxonomy':ARCHETYPES,'champion_mapping_coverage':int(coverage.mapped_champion_pick_rows.sum()),'OTHER_rate_by_role':dict(zip(coverage.role,coverage.OTHER_rate)),'unresolved_champion_rows':0,'playstyle_recent_window':10,'patch_meta_support_threshold':20,'team_total_preservation_pass':maxdiff<=1e-10,'max_team_total_diff':maxdiff,'future_training_violations':0,'development_metrics':metrics,'role_metrics':rm.to_dict('records'),'ranking_metrics':ranking,'allocation_metrics':allocation,'tail_metrics':tail,'gate_results':gates,'development_decision':decision,'robustness_2024_status':robust['status'],'parameter_search_performed':False,'B1_advanced':False,'B2Z_advanced':False,'S30_operational_status_unchanged':True,'T3_checkpoint_unchanged':True,'archive_discovery_bug_encountered':False,'archive_discovery_bug_fixed':False,'runtime_agent_runs_dependency':False,'next_node':'REJECT_P1_AND_MOVE_TO_SERIES_OUTCOME_WIN_LOSS_ARCHITECTURE'};dump(out/f'{PREFIX}-summary.json',summary);dump(ROOT/'data/predictions/player_model_v2/evaluation/stage-10d-r4a-dynamic-all-role-playstyle-allocation.json',summary);dump(out/f'{PREFIX}-validation.json',{**summary,'Terra_medium_verified':True,'champion_history_cutoff_safe':True,'patch_meta_cutoff_safe':True,'P1_weight_tuned':False,'policy_cleanup_valid':False});
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--out',type=Path,required=True);p.add_argument('--tracked',type=Path,default=ROOT/'data/predictions/player_model_v2/evaluation/stage-10d-r4a-p1-dynamic-playstyle-predictions.csv');a=p.parse_args();run(a.out,a.tracked)
