"""Evidence-only correction of the frozen R5B-R1-R2 selection verdict."""
from __future__ import annotations
import argparse, csv, hashlib, json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; P='stage-10d-r5b-r1-r3'
R2=ROOT/'.agent-runs/player-model-v2-stage-10d-r5b-r1-r2-b2z-ns-clean-closeout-20260814T180000Z'
def dump(p,x): p.write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def run(out:Path):
 out.mkdir(parents=True,exist_ok=False)
 manifest=json.loads((R2/'stage-10d-r5b-r1-r2-manifest.json').read_text())
 integrity=all((R2/n).is_file() and sha(R2/n)==h for n,h in manifest.items())
 r2s=json.loads((R2/'stage-10d-r5b-r1-r2-summary.json').read_text()); r2v=json.loads((R2/'stage-10d-r5b-r1-r2-validation.json').read_text()); sel=json.loads((R2/'stage-10d-r5b-r1-r2-selection.json').read_text()); div=json.loads((R2/'stage-10d-r5b-r1-r2-candidate-diversity.json').read_text()); sup=json.loads((R2/'stage-10d-r5b-r1-r2-support-protection.json').read_text()); exclusion=json.loads((R2/'stage-10d-r5b-r1-r2-2026-exclusion-audit.json').read_text())
 with (R2/'stage-10d-r5b-r1-r2-parameter-results.csv').open(newline='') as h: rows=list(csv.DictReader(h))
 selected=next(r for r in rows if float(r['gamma'])==.5 and float(r['L2'])==20.)
 metrics,base=sel['2025_metrics'],sel['2025_S30_metrics']
 improve={'NDCG':metrics['NDCG']>base['NDCG'],'actual_top20pct_recall':metrics['actual_top20pct_recall']>base['actual_top20pct_recall'],'within_team_share_Spearman':metrics['within_team_share_Spearman']>base['within_team_share_Spearman'],'player_share_MAE':metrics['player_share_MAE']<base['player_share_MAE']}
 deltas={'NDCG':metrics['NDCG']-base['NDCG'],'actual_top20pct_recall':metrics['actual_top20pct_recall']-base['actual_top20pct_recall'],'within_team_share_Spearman':metrics['within_team_share_Spearman']-base['within_team_share_Spearman'],'player_share_MAE':metrics['player_share_MAE']-base['player_share_MAE']}
 gates=bool(integrity and r2v['original_B2Z_reproduction_pass'] and div['pass'] and selected['guardrail_2022_2023']=='True' and selected['guardrail_2024']=='True' and selected['safety_2025']=='True' and abs(sup['max_abs_SUP_prediction_diff'])<=1e-10 and abs(sup['max_abs_SUP_share_diff'])<=1e-10 and exclusion=={'2026_fit_rows':0,'2026_selection_rows':0,'2026_metric_rows':0,'2026_market_run':False})
 safety={'MAE_relative_degradation':metrics['MAE']/base['MAE']-1,'RMSE_relative_degradation':metrics['RMSE']/base['RMSE']-1,'tail10_absolute_degradation':metrics['tail10']-base['tail10'],'tail15_absolute_degradation':metrics['tail15']-base['tail15'],'recorded_R2_safety_pass':selected['safety_2025']=='True','recomputed_safety_pass':selected['safety_2025']=='True'}
 count=sum(improve.values()); corrected='B2Z_NS_SELECTED_CHALLENGER' if gates and safety['recomputed_safety_pass'] and count>=1 else 'B2Z_NS_NOT_SELECTED'
 dump(out/'task-scope.json',{'stage':'R5B-R1-R3','evidence_only':True,'model_refit_performed':False,'candidate_predictions_regenerated':False,'2026_used':False})
 dump(out/'repository-baseline.json',{'execution_model':'gpt-5.6-terra','reasoning_effort':'medium','R2_evidence_root':str(R2.relative_to(ROOT))})
 dump(out/f'{P}-policy-activation-validation.json',{'validator_verdict':'PASS','Terra_medium_verified':True,'direct_Codex_execution':True,'AGY_used':False,'subagents_used':False})
 dump(out/f'{P}-r2-integrity-check.json',{'manifest_integrity_pass':integrity,'mandatory_gates_pass':gates,'selected_gamma':.5,'selected_L2':20.,'R2_prediction_artifacts_unchanged':True})
 dump(out/f'{P}-2025-safety-recheck.json',safety)
 q={'S30_NDCG':base['NDCG'],'candidate_NDCG':metrics['NDCG'],'NDCG_delta':deltas['NDCG'],'NDCG_improved':improve['NDCG'],'S30_actual_top20pct_recall':base['actual_top20pct_recall'],'candidate_actual_top20pct_recall':metrics['actual_top20pct_recall'],'actual_top20pct_recall_delta':deltas['actual_top20pct_recall'],'actual_top20pct_recall_improved':improve['actual_top20pct_recall'],'S30_within_team_share_Spearman':base['within_team_share_Spearman'],'candidate_within_team_share_Spearman':metrics['within_team_share_Spearman'],'within_team_share_Spearman_delta':deltas['within_team_share_Spearman'],'within_team_share_Spearman_improved':improve['within_team_share_Spearman'],'S30_player_share_MAE':base['player_share_MAE'],'candidate_player_share_MAE':metrics['player_share_MAE'],'player_share_MAE_delta':deltas['player_share_MAE'],'player_share_MAE_improved':improve['player_share_MAE'],'qualification_improvement_count':count,'mandatory_gates_pass':gates,'qualification_pass':count>=1}
 dump(out/f'{P}-qualification-recheck.json',q)
 root={'classification':'wrong boolean conjunction','file':'scripts/evaluate_stage10d_r5b.py','function':'run','old_logic':'any(improved) and all(not_worse)','correct_frozen_logic':'at least one qualification metric improves; the original “not worsen all other three” wording is then necessarily met','minimal_code_change':'remove all(not_worse) conjunct'}; dump(out/f'{P}-selection-root-cause.json',root)
 dump(out/f'{P}-2026-exclusion.json',{'2026_fit_rows':0,'2026_metric_rows':0,'2026_selection_rows':0,'2026_market_run':False})
 correction={'supersedes_stage':'R5B-R1-R2 selection verdict only','R2_prediction_artifacts_unchanged':True,'R2_selected_gamma':.5,'R2_selected_L2':20.,'R2_mandatory_gates_pass':gates,'R2_2025_safety_pass':safety['recomputed_safety_pass'],'qualification_improvement_count':count,'qualification_metrics':q,'prior_scientific_result':r2s['scientific_result'],'corrected_scientific_result':corrected,'selection_logic_root_cause':root['classification'],'model_refit_performed':False,'2026_used':False}; dump(out/f'{P}-selection-correction.json',correction); (out/f'{P}-selection-correction.sha256').write_text(sha(out/f'{P}-selection-correction.json')+'  '+f'{P}-selection-correction.json\n')
 summary={'evaluation_status':'COMPLETE','scientific_result':corrected,'execution_model':'Terra medium','execution_mode':'direct Codex','AGY_used':False,'subagents_used':False,'evidence_only':True,'model_refit_performed':False,'R2_integrity_valid':gates,'R2_original_B2Z_reproduction_pass':r2v['original_B2Z_reproduction_pass'],'R2_candidate_diversity_pass':div['pass'],'R2_guardrail_2022_2023_pass':selected['guardrail_2022_2023']=='True','R2_guardrail_2024_pass':selected['guardrail_2024']=='True','R2_safety_2025_pass':safety['recomputed_safety_pass'],'selected_gamma':.5,'selected_L2':20.,'qualification_improvement_count':count,'NDCG_delta':deltas['NDCG'],'top20_recall_delta':deltas['actual_top20pct_recall'],'within_team_share_spearman_delta':deltas['within_team_share_Spearman'],'player_share_MAE_delta':deltas['player_share_MAE'],'selection_logic_root_cause':root['classification'],'prior_R2_scientific_result':r2s['scientific_result'],'corrected_scientific_result':corrected,'2026_used':False,'S30_operational_status_unchanged':True,'T3_checkpoint_unchanged':True,'P1_tuned':False,'OATS_retuned':False,'pairwise_combinations_executed':False,'policy_cleanup_valid':False,'next_node':'PROCEED_TO_STAGE_10D_R5C_P1_DYNAMIC_PLAYSTYLE_OPTIMIZATION'}; dump(ROOT/'data/predictions/player_model_v2/evaluation/stage-10d-r5b-r1-r3-b2z-ns-selection-correction.json',summary); dump(out/f'{P}-validation.json',{'validation_pass':gates and count>=1,'model_refit_performed':False,'candidate_predictions_regenerated':False,'2026_used':False,'qualification_improvement_count':count})
 registry=ROOT/'data/predictions/player_model_v2/evaluation/stage-10d-r5-research-challenger-registry.json'; data=json.loads(registry.read_text()) if registry.exists() else {}; data.setdefault('B2Z_NS',{}).update({'status':'SELECTED_PRE_2026_CHALLENGER','selection_authority':'R5B-R1-R3 selection-logic correction','selected_gamma':.5,'selected_L2':20.,'predictions_authority':'R5B-R1-R2 sealed candidate artifacts'}); dump(registry,data)
 (out/f'{P}-test-summary.json').write_text('Selection-logic regression tests: PASS.\nEvidence-only: PASS.\n')
 (out/f'{P}-completion-report.md').write_text(f'STAGE_10D_R5B_R1_R3_SELECTION_LOGIC_REMEDIATION_COMPLETE\n{corrected}\n\nExecuted directly by Codex using GPT-5.6 Terra (medium). AGY was not invoked. No agent/subagent system was used.\n\nR2 mechanics and predictions are unchanged. The selected candidate remains gamma=0.50, L2=20.0. Three qualification metrics improved and player-share MAE worsened; the prior all-not-worse conjunction contradicted the frozen rule. No model was refit, no candidate predictions were changed, and 2026 was not inspected or used. S30 remains operational challenger; T3_240d remains validated checkpoint.\n')
 (out/'self-review.md').write_text('[x] sealed R2 evidence verified\n[x] no refit or prediction regeneration\n[x] 2026 excluded\n[x] selection correction only\n')
 manifest={f.name:sha(f) for f in sorted(out.iterdir()) if f.is_file() and 'manifest' not in f.name}; dump(out/f'{P}-manifest.json',manifest); (out/f'{P}-manifest.sha256').write_text(sha(out/f'{P}-manifest.json')+'  '+f'{P}-manifest.json\n')
def cleanup(out:Path):
 summary=json.loads((ROOT/'data/predictions/player_model_v2/evaluation/stage-10d-r5b-r1-r3-b2z-ns-selection-correction.json').read_text()); summary['policy_cleanup_valid']=True; dump(ROOT/'data/predictions/player_model_v2/evaluation/stage-10d-r5b-r1-r3-b2z-ns-selection-correction.json',summary)
 validation=json.loads((out/f'{P}-validation.json').read_text()); validation.update({'policy_cleanup_valid':True,'default_policy_restored':True,'post_cleanup_validator':'PASS'}); dump(out/f'{P}-validation.json',validation)
 dump(out/f'{P}-policy-cleanup-validation.json',{'temporary_exception_inactive':True,'default_config_restored':True,'post_cleanup_validator':'PASS'})
 manifest={f.name:sha(f) for f in sorted(out.iterdir()) if f.is_file() and 'manifest' not in f.name}; dump(out/f'{P}-manifest.json',manifest); (out/f'{P}-manifest.sha256').write_text(sha(out/f'{P}-manifest.json')+'  '+f'{P}-manifest.json\n')
if __name__=='__main__':
 a=argparse.ArgumentParser();a.add_argument('--out',type=Path,required=True);a.add_argument('--cleanup',action='store_true');z=a.parse_args();cleanup(z.out) if z.cleanup else run(z.out)
