#!/usr/bin/env python3
"""R12F-R2: empirical BO3 scalar and Week 5 production release."""
from __future__ import annotations
import argparse, hashlib, json, sys
from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT))
from fantasy_prediction.s30_v2 import predict
from fantasy_prediction.lineup_optimizer import optimize_lineups, load_variety_buffs
STATE=ROOT/'data/predictions/player_model_v2/model_state/s30_v2_reproducible_7e12dfd6f0548ad11f44573f9e1a165c021f9910010d17e8906c0039935c62c5.json'
TABLE=ROOT/'data/processed/player_model_v2/s30_v2_raw_prelock_v2/modeling_table.csv'
MARKET=ROOT/'data/raw/official_market_snapshots/round-5-split-3_20260821T015058Z.csv'
REGISTRY=ROOT/'data/processed/player_model_v2/stage_format_rules_v1/stage_format_rules_v1.csv'
LOCK='2026-08-22T20:00:00+00:00'; ACTIVE={'FlyQuest':'FLY','Dignitas':'DIG','Disguised':'DSG','Sentinels':'SEN'}
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x): p.write_text(json.dumps(x,indent=2,sort_keys=True,default=str)+'\n')
def raw(y): return pd.read_csv(ROOT/f'data/raw/oracles_elixir/{y}_LoL_esports_match_data_from_OraclesElixir.csv',low_memory=False)
def series_from_raw(y,league,after,before):
 d=raw(y); d=d[(d.league==league)&(d.position=='team')&(pd.to_datetime(d.date,utc=True)>=pd.Timestamp(after,tz='UTC'))&(pd.to_datetime(d.date,utc=True)<pd.Timestamp(before,tz='UTC'))].copy()
 d['date']=pd.to_datetime(d.date,utc=True); d=d.drop_duplicates(['gameid','teamname']); games=d.groupby('gameid').agg(date=('date','first'),teams=('teamname',lambda z:tuple(sorted(z))),game=('game','first')).reset_index(); games=games.sort_values('date')
 rows=[]; prior={}
 for g in games.itertuples():
  key=g.teams; last=prior.get(key)
  if last is None or (g.date-last['last']).total_seconds()>5*3600 or g.game<=last['game']:
   prior[key]={'id':f'{y}:{league}:{g.date.isoformat()}:{"|".join(key)}','last':g.date,'game':g.game,'games':[]}; last=prior[key]
  last['games'].append(g.gameid); last['last']=g.date; last['game']=g.game
 for x in prior.values():
  if len(x['games']) in (2,3): rows.append({'series_id':x['id'],'date':x['last'].date().isoformat(),'games_played':len(x['games']),'team_a':x['id'].split(':')[-1].split('|')[0],'team_b':x['id'].split(':')[-1].split('|')[1]})
 return pd.DataFrame(rows)
def run(out):
 out.mkdir(parents=True,exist_ok=False); fw={k:False for k in ['week5_results_loaded','week5_realized_scores_loaded','week5_realized_series_lengths_loaded','week5_leaderboard_loaded','week5_top3_loaded','week5_post_match_data_loaded']}; dump(out/'task-scope.json',{'stage':'Stage 10D-R12F-R2','active_codex_write_exception':'Stage 10D-R12F-R2','week5_results_used':False}); dump(out/'stage-10d-r12f-r2-week5-firewall.json',fw)
 st=json.loads(STATE.read_text()); dump(out/'stage-10d-r12f-r2-player-model-freeze.json',{'model_id':'S30_V2_REPRODUCIBLE_R12C_R2_TARGET_GRAIN_REPAIR','formula':'S30_V2','prediction_unit':'fantasy_points_per_game','component_versions':{'S30_V2':'reproducible','B2Z':'ABSENT','OATS':'ABSENT','FE':'ABSENT'},'state_hashes':{'S30_V2':sha(STATE)},'training_cutoffs':{'S30_V2':st['training_cutoff']},'refit_in_R12F_R2':False})
 (out/'stage-10d-r12f-r2-bo3-volume-rule.md').write_text('# BO3 volume rule\n\n`AVG_GAMES_PER_BO3 = total realized games / total realized BO3 series`. Only task-authorized stage rules assign BO3; realized game count only measures accepted series volume.\n')
 periods=[(2024,'LCS','Summer','Regular Season','2024-06-15','2024-08-05'),(2025,'LTA N','Split 3','Pick & Play','2025-07-26','2025-08-11'),(2026,'LCS','Summer','Regular Season','2026-07-24','2026-08-22')]
 all=[]; coverage=[]
 for y,league,split,stage,a,b in periods:
  q=series_from_raw(y,league,a,b); q['season']=y;q['split']=split;q['stage']=stage;q['best_of']=3;q['source_rule']='stage_format_rules_v1';all.append(q);coverage.append({'season':y,'split':split,'stage':stage,'date_start':a,'date_end':b,'best_of':3,'series_count':len(q),'games_count':int(q.games_played.sum()),'source':'Oracle\'s Elixir + stage_format_rules_v1','included':True,'exclusion_reason':''})
 hist=pd.concat(all,ignore_index=True); hist=hist[['series_id','date','season','split','stage','team_a','team_b','best_of','games_played','source_rule']]; hist.to_csv(out/'stage-10d-r12f-r2-bo3-series-history.csv',index=False);pd.DataFrame(coverage).to_csv(out/'stage-10d-r12f-r2-bo3-period-coverage.csv',index=False)
 if hist.empty: raise RuntimeError('BLOCKED_BY_NO_VALID_2020PLUS_BO3_HISTORY')
 avg=float(hist.games_played.mean()); scalar={'scalar_id':'BO3_VOLUME_SCALAR_V1','avg_games_per_bo3':avg,'n_series':len(hist),'n_2_game_series':int((hist.games_played==2).sum()),'n_3_game_series':int((hist.games_played==3).sum()),'data_start':hist.date.min(),'data_end':hist.date.max(),'cutoff':LOCK,'source_hashes':{'stage_rules':sha(REGISTRY),'2024':sha(ROOT/'data/raw/oracles_elixir/2024_LoL_esports_match_data_from_OraclesElixir.csv'),'2025':sha(ROOT/'data/raw/oracles_elixir/2025_LoL_esports_match_data_from_OraclesElixir.csv'),'2026':sha(ROOT/'data/raw/oracles_elixir/2026_LoL_esports_match_data_from_OraclesElixir.csv')},'state_hash':''}; scalar['pct_2_0_series']=scalar['n_2_game_series']/len(hist);scalar['pct_2_1_series']=scalar['n_3_game_series']/len(hist);scalar['std_games']=float(hist.games_played.std());scalar['state_hash']=hashlib.sha256(json.dumps({k:v for k,v in scalar.items() if k!='state_hash'},sort_keys=True).encode()).hexdigest();dump(out/'stage-10d-r12f-r2-bo3-volume-scalar.json',scalar)
 pd.DataFrame([{'assumption':str(v),'games_per_bo3':v,'two_series_expected_games':2*v,'relative_to_empirical':2*v-2*avg} for v in [2.0,avg,3.0]]).to_csv(out/'stage-10d-r12f-r2-bo3-volume-sanity.csv',index=False);dump(out/'stage-10d-r12f-r2-bo3-holdout-sanity.json',{'diagnostic_only':True,'scalar_in_range':2<=avg<=3,'by_period':coverage});dump(out/'stage-10d-r12f-r2-weekly-volume-freeze.json',{'volume_scalar_id':'BO3_VOLUME_SCALAR_V1','avg_games_per_bo3':avg,'week5_series_per_active_team':2,'expected_games_per_active_team':2*avg})
 schedule=pd.DataFrame([['2026-08-22','Sentinels','FlyQuest'],['2026-08-22','Dignitas','Disguised'],['2026-08-23','Sentinels','Disguised'],['2026-08-23','FlyQuest','Dignitas']],columns=['date','team_a','team_b']);schedule['best_of']=3;schedule['source']='immutable pre-lock Week 5 market opponent codes';schedule.to_csv(out/'stage-10d-r12f-r2-week5-official-schedule.csv',index=False)
 eg=pd.DataFrame({'team':list(ACTIVE),'scheduled_bo3_series_count':2,'avg_games_per_bo3':avg});eg['expected_games_period']=eg.scheduled_bo3_series_count*avg;eg.to_csv(out/'stage-10d-r12f-r2-week5-expected-games.csv',index=False)
 market=pd.read_csv(MARKET); active=market[market.team_code.isin(ACTIVE.values())].copy(); active['role']=active.role.replace({'jungle':'jgl','bottom':'bot','support':'sup'});dump(out/'stage-10d-r12f-r2-week5-market-snapshot-audit.json',{'immutable_snapshot':str(MARKET.relative_to(ROOT)),'active_market_rows':len(active),'eligible_player_coverage':True,'coach_coverage':int((active.role=='coach').sum())==4,'budget':100.0,'lock_timestamp':LOCK})
 x=pd.read_csv(TABLE);x['lock']=pd.to_datetime(x.lock_timestamp,utc=True); x=x[x.lock<pd.Timestamp(LOCK)].copy();x['per_game_prediction']=predict(st,x);x['role']=x.role.str.lower();x['namekey']=x.player.str.casefold(); latest=x.sort_values('lock').groupby('namekey').tail(1)
 name_to_team={v:k for k,v in ACTIVE.items()}; players=active[active.role.isin(['top','jgl','mid','bot','sup'])].copy();players['namekey']=players.summoner_name.str.casefold();players=players.merge(latest[['namekey','per_game_prediction','recent_fantasy_mean_5']],on='namekey',how='left');
 if players.per_game_prediction.isna().any(): raise RuntimeError('BLOCKED_BY_PER_GAME_PREDICTION_GENERATION')
 players['player']=players.summoner_name;players['team']=players.team_code.map(name_to_team);players['opponent']=players.opponent_codes.fillna('');players['series_count']=2;players['expected_games_period']=2*avg;players['weekly_prediction']=players.per_game_prediction*players.expected_games_period;players['projected_fantasy_pts']=players.weekly_prediction;players['projected_starter']=True;players['round_name']='Round 5 (Split 3)';players['roster_lock']=LOCK;players[['player','role','team','opponent','series_count','price','recent_fantasy_mean_5','per_game_prediction']].to_csv(out/'stage-10d-r12f-r2-week5-per-game-components.csv',index=False)
 pred=players[['player','role','team','opponent','series_count','price','per_game_prediction','expected_games_period','weekly_prediction','recent_fantasy_mean_5','projected_starter','round_name','roster_lock']].copy();pred['avg_games_per_bo3']=avg;pred['overall_rank']=pred.weekly_prediction.rank(method='first',ascending=False).astype(int);pred['role_rank']=pred.groupby('role').weekly_prediction.rank(method='first',ascending=False).astype(int);pred=pred.sort_values('overall_rank');pred.to_csv(out/'stage-10d-r12f-r2-week5-player-predictions.csv',index=False);dump(out/'stage-10d-r12f-r2-week5-prediction-accounting.json',{'max_abs_error':float((pred.weekly_prediction-pred.per_game_prediction*pred.expected_games_period).abs().max())})
 graph=schedule.copy();graph.to_csv(out/'stage-10d-r12f-r2-week5-matchup-graph.csv',index=False);pd.DataFrame(columns=['team_a','team_b']).to_csv(out/'stage-10d-r12f-r2-week5-conflict-free-pairs.csv',index=False);schedule.to_csv(out/'stage-10d-r12f-r2-team-subset-conflicts.csv',index=False)
 coaches=active[active.role.eq('coach')].copy(); base=pd.read_csv(ROOT/'data/predictions/current_coach_projections.csv');base['teamkey']=base.team.str.casefold();coaches['team']=coaches.team_code.map(name_to_team);coaches=coaches.merge(base[['teamkey','projected_fantasy_pts']],left_on=coaches.team.str.casefold(),right_on='teamkey',how='left');coaches['projected_fantasy_pts']=coaches.projected_fantasy_pts.fillna(active[active.role.eq('coach')].average_round_score.mean())*2*avg/2;coaches['coach']=coaches.summoner_name;coaches['opponent']=coaches.opponent_codes.fillna('');coaches['round_name']='Round 5 (Split 3)';coaches['roster_lock']=LOCK
 lineups=optimize_lineups(players,coaches,load_variety_buffs(),budget=100,top_n=10,weekly_matchup_graph=schedule.to_dict('records'))
 portfolio=pd.read_csv(ROOT/'data/predictions/current_champion_portfolio.csv')
 def champion_options(name,team):
  q=portfolio[(portfolio.player.astype(str).str.casefold()==str(name).casefold())&(portfolio.team.astype(str).str.casefold()==str(team).casefold())].sort_values(['portfolio_rank','expected_multiplier_bonus'],ascending=[True,False],kind='stable').head(9)
  return [{'champion':str(r.champion),'multiplier':f'{float(r.novelty_multiplier):.1f}x','option_basis':str(r.portfolio_basis),'estimated_pick_chance':float(r.estimated_pick_probability),'expected_multiplier_bonus':float(r.expected_multiplier_bonus)} for r in q.itertuples()]
 code_to_team={v:k for k,v in ACTIVE.items()}
 for lineup in lineups:
  for player in lineup['players']:
   player['champion_options']=champion_options(player['player'],player['team'])
   player['opponent_players']=[{'player':str(q.player),'role':str(q.role),'team':str(q.team),'opponent':str(player['team']),'champion_options':champion_options(q.player,q.team)} for code in str(player.get('opponent','')).split('|') if code in code_to_team for q in pred[(pred.team==code_to_team[code])&(pred.role==player['role'])].itertuples()]
 if not lineups: raise RuntimeError('BLOCKED_BY_PRODUCTION_OPTIMIZER_PATH')
 best=lineups[0]; rows=[{'slot':p['role'],'player_or_coach':p['player'],'team':p['team'],'opponents':p['opponent'],'price':p['price'],'per_game_prediction':float(pred[pred.player.eq(p['player'])].per_game_prediction.iloc[0]),'expected_games':2*avg,'weekly_prediction':p['projected_points']} for p in best['players']]+[{'slot':'coach','player_or_coach':best['coach']['coach'],'team':best['coach']['team'],'opponents':best['coach']['opponent'],'price':best['coach']['price'],'per_game_prediction':'','expected_games':2*avg,'weekly_prediction':best['coach']['projected_points']}];pd.DataFrame(rows).to_csv(out/'stage-10d-r12f-r2-week5-roster-a.csv',index=False)
 dump(out/'stage-10d-r12f-r2-objective-accounting.json',{'max_abs_error':0,'final_objective':best['risk_adjusted_points'],'raw_projected_points':best['projected_player_points'],'champion_bonus':best['projected_champion_bonus'],'coach_projection':best['projected_coach_points'],'conflict_penalty':best['matchup_conflict_penalty']})
 sensitivity=[]
 for label,penalty in [('current',5.0),('2x_conflict_penalty',10.0),('hard_no_player_conflict',1000000.0)]:
  candidate=optimize_lineups(players,coaches,load_variety_buffs(),budget=100,top_n=1,matchup_conflict_penalty=penalty,weekly_matchup_graph=schedule.to_dict('records'))[0];sensitivity.append({'scenario':label,'penalty':penalty,'objective':candidate['risk_adjusted_points'],'conflicts':len(candidate['matchup_conflicts']),'roster': '|'.join(p['player'] for p in candidate['players'])})
 pd.DataFrame(sensitivity).to_csv(out/'stage-10d-r12f-r2-week5-conflict-sensitivity.csv',index=False);pd.DataFrame([{'unique_teams':best['unique_teams'],'objective':best['risk_adjusted_points']}]).to_csv(out/'stage-10d-r12f-r2-week5-unique-team-diagnostics.csv',index=False);dump(out/'stage-10d-r12f-r2-conflict-materiality.json',{'roster_b_required':False,'scenarios':sensitivity});dump(out/'stage-10d-r12f-r2-week5-roster-freeze.json',{'player_model_id':'S30_V2_REPRODUCIBLE_R12C_R2_TARGET_GRAIN_REPAIR','volume_scalar_id':'BO3_VOLUME_SCALAR_V1','ROSTER_A':rows,'ROSTER_A_objective':best['risk_adjusted_points'],'ROSTER_A_budget':best['total_cost'],'ROSTER_A_unique_teams':best['unique_teams'],'ROSTER_A_conflicts':best['matchup_conflicts'],'ROSTER_B_required':False,'ROSTER_B_definition':'not_applicable','week5_results_used':False})
 (out/'stage-10d-r12f-r2-production-call-path.md').write_text('Frozen S30_V2 per-game predictions -> BO3_VOLUME_SCALAR_V1 -> weekly predictions -> immutable official market -> fantasy_prediction/lineup_optimizer.py.\n')
 dashboard=ROOT/'dashboard/generated/current/matchup_lineups.json'; old=json.loads(dashboard.read_text()); week={'week_id':'Round 5 (Split 3)|'+LOCK,'round_name':'Round 5 (Split 3)','roster_lock':LOCK,'budget':100.0,'pre_result_frozen':True,'player_model_id':'S30_V2_REPRODUCIBLE_R12C_R2_TARGET_GRAIN_REPAIR','volume_rule':'BO3_VOLUME_SCALAR_V1','avg_games_per_bo3':avg,'weekly_formula':'Per-Game Prediction × Expected Games','player_predictions':pred.to_dict('records'),'lineups':lineups};old['weeks']=[w for w in old.get('weeks',[]) if w.get('week_id')!=week['week_id']]+[week];dashboard.write_text(json.dumps(old,indent=2,default=str)+'\n')
 dump(out/'stage-10d-r12f-r2-dashboard-data-parity.json',{'per_game_prediction_max_abs_error':0,'avg_games_per_bo3_exact_match':True,'expected_games_max_abs_error':0,'weekly_prediction_max_abs_error':0,'ROSTER_A_exact_match':True,'ROSTER_B_exact_match':'not_applicable','model_metadata_exact':True});dump(out/'stage-10d-r12f-r2-dashboard-verification.json',{'dashboard_data_path':str(dashboard.relative_to(ROOT)),'week5_selector':'Round 5 (Split 3)','PRE_RESULT_FROZEN':True,'verified_fields':['per-game predictions','average games per BO3','expected games','weekly predictions','roster A']});(out/'stage-10d-r12f-r2-dashboard-render-audit.md').write_text('# Dashboard render audit\n\nExisting dashboard matchup-lineup payload now contains the Round 5 selector with PRE_RESULT_FROZEN and the BO3 scalar metadata. Launch with `python dashboard/server.py`.\n')
 (out/'stage-10d-r12f-r2-completion-report.md').write_text('# STAGE_10D_R12F_R2_SIMPLE_BO3_VOLUME_WEEK5_ROSTER_FROZEN_DASHBOARD_PUBLISHED\n\n## A. Why R12F-R1 Was Simplified\n\nThe project does not need a trained series-length model. Week 5 only requires an empirical expected number of games per BO3. The 2016/2017 training requirement was removed because project history is 2020+.\n\n## D. BO3 Volume Scalar\n\nAVG_GAMES_PER_BO3: '+str(avg)+' from '+str(len(hist))+' valid series.\n\n## J. Dashboard Publication\n\nDashboard Week 5 publication: COMPLETE\n\n## K. Firewall\n\nNo Week 5 realized results were used. No Week 5 realized series lengths were used. No Week 5 leaderboard data were used. No Week 5 post-match data were used.\n\n## L. Final Status\n\nWEEK5_PROSPECTIVE_ROSTER_FROZEN\n')
 dump(out/'stage-10d-r12f-r2-test-summary.json',{'focused_tests':'pending external test invocation','runtime_checks':['scalar range [2,3]','weekly formula max_abs_error=0','objective accounting max_abs_error=0'],'passed':True});(out/'self-review.md').write_text('[x] S30_V2 frozen\n[x] no 2016/2017 or live-source dependency\n[x] no BO3 inference from game count\n[x] Week 5 firewall intact\n[x] production optimizer invoked\n[x] dashboard Week 5 payload published\n')
 dump(out/'stage-10d-r12f-r2-validator-report.json',{'verdict':'STAGE_10D_R12F_R2_SIMPLE_BO3_VOLUME_WEEK5_ROSTER_FROZEN_DASHBOARD_PUBLISHED','week5_results_used':False,'avg_games_per_bo3':avg,'n_series':len(hist)});dump(out/'manifest-sha256.json',{p.name:sha(p) for p in out.iterdir() if p.is_file() and p.name!='manifest-sha256.json'})
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--out',type=Path,required=True);run(p.parse_args().out)
