#!/usr/bin/env python3
"""R12D raw-native candidate unit-contract gate."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
STATE=ROOT/'data/predictions/player_model_v2/model_state/s30_v2_reproducible_7e12dfd6f0548ad11f44573f9e1a165c021f9910010d17e8906c0039935c62c5.json'
R2=ROOT/'.agent-runs/player-model-v2-stage-10d-r12c-r2-unified-context-final-week5-20260821T053045Z'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x):p.write_text(json.dumps(x,indent=2,sort_keys=True,default=str)+'\n')
def run(out):
 out.mkdir(parents=True,exist_ok=False);firewall={'week5_results_loaded':False,'week5_realized_scores_loaded':False,'week5_leaderboard_loaded':False,'week5_top3_loaded':False,'week5_post_match_data_loaded':False};dump(out/'task-scope.json',{'stage':'Stage 10D-R12D','active_codex_write_exception':'Stage 10D-R12D','week5_results_used':False});dump(out/'stage-10d-r12d-week5-firewall.json',firewall)
 st=json.loads(STATE.read_text());r2=json.loads((R2/'stage-10d-r12c-r2-s30-v2-sanity-decision.json').read_text());dump(out/'stage-10d-r12d-s30-v2-freeze.json',{'state_path':str(STATE.relative_to(ROOT)),'state_hash':sha(STATE),'target_grain':'game_average','training_cutoff':st['training_cutoff'],'feature_order':st['feature_order'],'alpha':st['alpha'],'2024_MAE':r2['quality_evidence']['2024']['player_MAE'],'2025_MAE':r2['quality_evidence']['2025']['player_MAE'],'pooled_MAE':5.350098,'refit_in_R12D':False})
 dump(out/'stage-10d-r12d-b2z-lineage-decision.json',{'historical_B2Z_valid_as_historical_result':True,'B2Z_V2_prospective_eligible':False,'reason':'missing raw/pre-lock producer for serialized Stage 3E/4C/8 player/core/team/matchup state','B2Z_V3_is_new_model':True,'B2Z_V3_is_recovery':False})
 (out/'stage-10d-r12d-week5-unit-contract-audit.md').write_text('# BLOCKED_BY_WEEK5_CONTEXT_COVERAGE\n\nR12C-R2 froze S30_V2 at `player × local prediction period × game-average`. R12D defines B2Z_V3 residuals and FE allocations at that same unit. The official Week 5 market contains four best-of series, and each active team plays two series. The production optimizer requires one weekly fantasy-point value per player.\n\nNo sealed transformation converts a game-average score into expected points for two best-of series: it would need an explicit expected game-count/series aggregation contract. `multiseries_projection_adapter` only aggregates already-valid series predictions. Prior R7C-R6, R10, and R11 all document that duplicating/scaling S30 without that contract is prohibited. R12D authorizes a new raw-native B2Z residual model but does not authorize selecting or inventing a game-count mapping. Consequently a Week 5 player prediction, optimizer objective, roster, and dashboard record cannot be made without changing the frozen model’s target semantics.\n')
 dump(out/'stage-10d-r12d-validator-report.json',{'verdict':'BLOCKED_BY_WEEK5_CONTEXT_COVERAGE','week5_results_used':False,'s30_target_grain':'game_average','week5_schedule_structure':'four series; each active team has two series','weekly_aggregation_contract_available':False,'reason':'No sealed raw/pre-lock mapping converts the frozen game-average S30/B2Z_V3/FE unit to expected weekly points over two best-of series. Series-count multiplication or assumed games per series would be a new, unvalidated model behavior.','prohibited_fallbacks':['duplicate per-game prediction per series','multiply by series count','assume best-of expected game length']})
 (out/'stage-10d-r12d-completion-report.md').write_text('# BLOCKED_BY_WEEK5_CONTEXT_COVERAGE\n\n## A. S30_V2 Freeze\n\nThe repaired S30 state is intact and was not refit. It predicts a game-average target.\n\n## B. B2Z_V2 Retirement\n\nB2Z_V2 is retired from prospective use because its serialized input producer is absent.\n\n## C. Week 5 Unit Contract\n\nR12D permits a raw-native B2Z successor, but that successor must share the game-average target grain. The Week 5 optimizer needs weekly points for two scheduled series. No frozen mapping specifies expected games per series or aggregation from a game average to a weekly score. Creating B2Z_V3/FE and then multiplying or duplicating predictions would introduce exactly the unapproved behavior prior gates rejected.\n\nNo Week 5 realized results were used.\nNo Week 5 leaderboard data were used.\nNo Week 5 post-match data were used.\n')
 (out/'self-review.md').write_text('[x] repaired S30 frozen\n[x] B2Z_V2 prospectively retired\n[x] Week 5 unit contract audited\n[x] no S30/B2Z/OATS refit\n[x] no FE retune\n[x] no invented series aggregation\n[x] Week 5 firewall intact\n')
 dump(out/'manifest-sha256.json',{p.name:sha(p) for p in out.iterdir() if p.is_file() and p.name!='manifest-sha256.json'})
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--out',type=Path,required=True);run(p.parse_args().out)
